/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole.OrganDonation;

import Business.Enterprise.Enterprise;
import Business.OrganDonation.OrganRecipient;
import Business.OrganDonation.OrganRecipientDirectory;
import Business.Organization.DoctorOrganization;
import Business.Organization.OrganBankOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrganRequest;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author akshayasuresh
 */
public class OrganRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrganRequestJPanel
     */
   private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private OrganRecipientDirectory ord;
    private int medicalID;
    private String organ;
   
   public OrganRequestJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, int medicalID) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.enterprise= enterprise;
       this.userAccount = userAccount;
       this.medicalID = medicalID;
       midLabel.setText(String.valueOf(medicalID));
       populateOrganComboBox();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        midLabel = new javax.swing.JLabel();
        priorityTxt = new javax.swing.JTextField();
        firstnameLbl8 = new javax.swing.JLabel();
        deadlineTxt = new javax.swing.JTextField();
        firstnameLbl9 = new javax.swing.JLabel();
        requestOrganBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        organComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        backBtn.setBackground(new java.awt.Color(255, 204, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(6, 6, 139, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Organ");
        add(jLabel6);
        jLabel6.setBounds(180, 100, 44, 17);

        midLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        add(midLabel);
        midLabel.setBounds(330, 50, 177, 20);

        priorityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityTxtActionPerformed(evt);
            }
        });
        add(priorityTxt);
        priorityTxt.setBounds(185, 165, 323, 30);

        firstnameLbl8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl8.setText("Priority");
        add(firstnameLbl8);
        firstnameLbl8.setBounds(179, 129, 90, 30);

        deadlineTxt.setText("MM-DD-YYYY");
        deadlineTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadlineTxtActionPerformed(evt);
            }
        });
        add(deadlineTxt);
        deadlineTxt.setBounds(185, 243, 323, 30);

        firstnameLbl9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl9.setText("Deadline");
        add(firstnameLbl9);
        firstnameLbl9.setBounds(179, 207, 90, 30);

        requestOrganBtn.setBackground(new java.awt.Color(255, 204, 51));
        requestOrganBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        requestOrganBtn.setText("Request Organ");
        requestOrganBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestOrganBtnActionPerformed(evt);
            }
        });
        add(requestOrganBtn);
        requestOrganBtn.setBounds(252, 326, 164, 39);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Medical Id ");
        add(jLabel7);
        jLabel7.setBounds(180, 50, 79, 17);

        organComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organComboBoxActionPerformed(evt);
            }
        });
        add(organComboBox);
        organComboBox.setBounds(320, 100, 96, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 720, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void priorityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityTxtActionPerformed

    private void deadlineTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadlineTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deadlineTxtActionPerformed

    private void requestOrganBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestOrganBtnActionPerformed
        // TODO add your handling code here:
              SimpleDateFormat ft = new SimpleDateFormat("MM-dd-yyyy");
                Date deadline = new Date();
               int priority= Integer.parseInt(priorityTxt.getText());
                
       try {
           deadline = ft.parse(deadlineTxt.getText());
       } catch (ParseException ex) {
           Logger.getLogger(OrganRequestJPanel.class.getName()).log(Level.SEVERE, null, ex);
       }
               
        for(OrganRecipient or: ord.getOrganRecipientList()){
            if(medicalID == or.getMedicalID() && or.getOrgan().equalsIgnoreCase(organ)){
                or.setPriority(priority);
                or.setDeadline(deadline);
                or.setOrgan(organ);
                
            
        OrganRequest request = new OrganRequest();
        request.setMedicalID(medicalID);
        request.setSender(userAccount);
        request.setOrganisation(enterprise.getName());
        request.setSenderNo(userAccount.getEmployee().getPhoneNumber());
        request.setStatus("Sent");
        request.setBloodGrp(or.getBloodGrp());
        request.setHlaType(or.getHlaType());
        request.setDeadline(deadline);
        request.setOrgansNeeded(organ);
        request.setPriority(priority);
        request.setWaitlistNo(or.getWaitlistNo());
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof OrganBankOrg){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        break;
        }
      }
        JOptionPane.showMessageDialog(null,"Organ requested successfully");
       
    }//GEN-LAST:event_requestOrganBtnActionPerformed

    private void organComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organComboBoxActionPerformed
        // TODO add your handling code here:
        organ = (String) organComboBox.getSelectedItem();
    }//GEN-LAST:event_organComboBoxActionPerformed
    private void populateOrganComboBox() {
            organComboBox.removeAllItems();
            String[] organs = {"R.Lung", "L.Lung", "Pancreas", "Intestine","Heart", "L.Kidney", "R.Kidney","Liver" };
            for(String o: organs){
                organComboBox.addItem(o);
            }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField deadlineTxt;
    private javax.swing.JLabel firstnameLbl8;
    private javax.swing.JLabel firstnameLbl9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel midLabel;
    private javax.swing.JComboBox<String> organComboBox;
    private javax.swing.JTextField priorityTxt;
    private javax.swing.JButton requestOrganBtn;
    // End of variables declaration//GEN-END:variables
}
