/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BloodcampRequest;
import Business.WorkQueue.WorkRequest;
import Business.bloodbankcampaign.bloodbankcampaignmember;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Bloodrequestjpanel extends javax.swing.JPanel {

    /**
     * Creates new form Bloodrequestjpanel
     */
      private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientOrganization patientOrg;
    Bloodrequestjpanel(JPanel userProcessContainer, UserAccount userAccount, PatientOrganization organization, Enterprise enterprise) {
      initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.patientOrg= organization;
        populateRequestTable();
    }
     public void populateRequestTable(){
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
           SimpleDateFormat formatter = new SimpleDateFormat("dd-MMM-yyyy");
       model.setRowCount(0);
        
      for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof BloodcampRequest)
            {
                Object[] row = new Object[6];
               row[0] = ((BloodcampRequest) request);
               row[1] =  ((BloodcampRequest) request).getSender();
               row[2] = ((BloodcampRequest) request).getLocation();
               
              String reportDate = formatter.format(((BloodcampRequest)request).getDate());
               row[3]=reportDate;
              row[4]=((BloodcampRequest)request).getStatus();
              row[5]=((BloodcampRequest)request).getResult();
                

                model.addRow(row);
            }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Location", "Date", "Status", "Result"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(160, 130, 430, 120);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Attend");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(240, 300, 108, 29);

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setText("Ignore");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(390, 300, 99, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -100, 1740, 1330);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (WorkRequest)jTable1.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Confirmed");
        ((BloodcampRequest)request).setResult("Accepted");
        populateRequestTable();
        
        bloodbankcampaignmember bbcm=new bloodbankcampaignmember();
        bbcm.setFirstName(userAccount.getPatient().getFirstName());
        bbcm.setMedicalId(userAccount.getPatient().getMedicalRecord().getMedicalId());
        bbcm.setUseraccount(userAccount);
        enterprise.getBbcampaigndirectory().addbloodbankcmember(bbcm);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (WorkRequest)jTable1.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Confirmed");
        ((BloodcampRequest)request).setResult("Ignored");
        
        populateRequestTable();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
