/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author akshayasuresh
 */
public class NotificationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotificationJPanel
     */
     private JPanel userProcessContainer;
    private PatientOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
 
   

   public NotificationJPanel(JPanel userProcessContainer, UserAccount userAccount, PatientOrganization organization, Enterprise enterprise) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageNetwork = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        manageNetwork1 = new javax.swing.JButton();

        setLayout(null);

        manageNetwork.setBackground(new java.awt.Color(255, 204, 51));
        manageNetwork.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        manageNetwork.setText("Doctor Request");
        manageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkActionPerformed(evt);
            }
        });
        add(manageNetwork);
        manageNetwork.setBounds(290, 190, 210, 40);

        backBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(70, 430, 96, 27);

        manageNetwork1.setBackground(new java.awt.Color(255, 204, 51));
        manageNetwork1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        manageNetwork1.setText("BloodbankRequest");
        manageNetwork1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetwork1ActionPerformed(evt);
            }
        });
        add(manageNetwork1);
        manageNetwork1.setBounds(290, 90, 210, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkActionPerformed
        DoctorRequestJPanel doctorRequestJPanel = new DoctorRequestJPanel(userProcessContainer,userAccount,organization,enterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DoctorRequestJPanel", doctorRequestJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void manageNetwork1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetwork1ActionPerformed
        // TODO add your handling code here:
           Bloodrequestjpanel bloodrequestjpanel = new Bloodrequestjpanel(userProcessContainer,userAccount,organization,enterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DoctorRequestJPanel",bloodrequestjpanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetwork1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton manageNetwork;
    private javax.swing.JButton manageNetwork1;
    // End of variables declaration//GEN-END:variables
}
