/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.OrganBank.OrganRegistration;

import Business.OrganDonation.OrganDonor;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author akshayasuresh
 */
public class DonorCardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorCardJPanel
     */
  
      private JPanel userProcessContainer;
      private OrganDonor od;

    public DonorCardJPanel(JPanel userProcessContainer, OrganDonor od) {
         initComponents();
        this.userProcessContainer = userProcessContainer;
        this.od = od;
        midLabel1.setText(String.valueOf(od.getMedicalID()));
        nameLabel.setText(od.getFname()+" "+od.getLname());
        noLabel.setText(String.valueOf(od.getEmergencyContactNo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editBtn1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        firstnameLbl = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        midLabel1 = new javax.swing.JLabel();
        firstnameLbl5 = new javax.swing.JLabel();
        noLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editBtn3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        editBtn1.setBackground(new java.awt.Color(255, 204, 51));
        editBtn1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        editBtn1.setText("Print Donor Card");
        editBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn1ActionPerformed(evt);
            }
        });
        add(editBtn1);
        editBtn1.setBounds(444, 420, 210, 40);

        backBtn.setBackground(new java.awt.Color(255, 204, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(6, 6, 164, 40);

        jPanel1.setLayout(null);

        nameLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(nameLabel);
        nameLabel.setBounds(233, 131, 108, 26);

        firstnameLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl.setText("Name ");
        jPanel1.add(firstnameLbl);
        firstnameLbl.setBounds(67, 131, 90, 30);

        photo.setText("jLabel1");
        jPanel1.add(photo);
        photo.setBounds(370, 65, 130, 161);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Donor Id ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(67, 75, 90, 57);

        midLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(midLabel1);
        midLabel1.setBounds(233, 87, 108, 26);

        firstnameLbl5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl5.setText("Emergency Contact");
        jPanel1.add(firstnameLbl5);
        firstnameLbl5.setBounds(67, 164, 159, 30);

        noLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(noLabel);
        noLabel.setBounds(232, 168, 114, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/proud-organ-donor640.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 560, 230);

        add(jPanel1);
        jPanel1.setBounds(149, 109, 551, 230);

        editBtn3.setBackground(new java.awt.Color(255, 204, 51));
        editBtn3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        editBtn3.setText("Email Donor Card");
        editBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn3ActionPerformed(evt);
            }
        });
        add(editBtn3);
        editBtn3.setBounds(176, 420, 210, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void editBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn1ActionPerformed
        
         PrinterJob pj = PrinterJob.getPrinterJob();
         pj.setJobName(" Print Donor Card ");
     
        pj.setPrintable (new Printable() {    
        @Override
        public int print(Graphics pg, PageFormat pf, int pageNum){
             if (pageNum > 0){
                 return Printable.NO_SUCH_PAGE;
        }

        Graphics2D g2 = (Graphics2D) pg;
         g2.translate(pf.getImageableX(), pf.getImageableY());
         jPanel1.paint(g2);
        return Printable.PAGE_EXISTS;
             }
            });
         if (pj.printDialog() == false)
                return;

             try {
                pj.print();
                } catch (PrinterException ex) {
                        System.out.println(ex);
            }


         
              
    }//GEN-LAST:event_editBtn1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void editBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtn3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton editBtn1;
    private javax.swing.JButton editBtn3;
    private javax.swing.JLabel firstnameLbl;
    private javax.swing.JLabel firstnameLbl5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel midLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel noLabel;
    private javax.swing.JLabel photo;
    // End of variables declaration//GEN-END:variables
}
