/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.OrganBank.OrganRegistration;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.MedicalId.MedicalIdDirectory;
import Business.MedicalId.MedicalRecord;
import Business.Network.Network;
import Business.OrganDonation.OrganDonor;
import Business.OrganDonation.OrganDonorDirectory;
import Business.Organization.OrganBankOrg;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author akshayasuresh
 */
public class DonorRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorRegistrationJPanel
     */
    private JPanel userProcessContainer;
    private OrganBankOrg organization;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    private MedicalIdDirectory medicalRecords;
    private OrganDonorDirectory odd;
    int checkAlreadyDonor=0;
    
    public DonorRegistrationJPanel(JPanel userProcessContainer, UserAccount userAccount, OrganBankOrg organization, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
            this.organization = (OrganBankOrg)organization;
            this.ecosystem = ecosystem;
            this.userAccount = userAccount;
            userProcessContainer.setSize(new Dimension(1000,1000));
            medicalRecords = new MedicalIdDirectory();
            HospitalEnterprise enterprise = null;
            
            for(Network network: ecosystem.getNetworkList()){
                for(Enterprise centerprise: network.getEnterpriseDirectory().getEnterpriseList()){
                    if(centerprise instanceof HospitalEnterprise){
                        enterprise= (HospitalEnterprise)centerprise;
                         for(MedicalRecord mr : enterprise.getMedicalIdDirec().getMedicalIdList()){
                        medicalRecords.getMedicalIdList().add(mr);
                        
                    }
                }
                }
                
            }
                for(MedicalRecord m: medicalRecords.getMedicalIdList()){
                    System.out.println(m.getMedicalId());
                }
            
            
           
            clearFields();
            registerBtn.setVisible(false);
            updateBtn.setVisible(false);
            withdrawBtn.setVisible(false);
            populateGenderComboBox();
            populateStateComboBox();
            odd = new OrganDonorDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        medicalIdTxt = new javax.swing.JTextField();
        firstnameLbl = new javax.swing.JLabel();
        firstnameTxt = new javax.swing.JTextField();
        lastnameLbl = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        sexLbl = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        dobLbl = new javax.swing.JLabel();
        dobTxt = new javax.swing.JTextField();
        regisLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        regisLbl2 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        firstnameLbl3 = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        firstnameLbl1 = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox<>();
        firstnameLbl2 = new javax.swing.JLabel();
        zipTxt = new javax.swing.JTextField();
        firstnameLbl4 = new javax.swing.JLabel();
        bloodTxt = new javax.swing.JTextField();
        firstnameLbl5 = new javax.swing.JLabel();
        emergencyContact = new javax.swing.JTextField();
        firstnameLbl6 = new javax.swing.JLabel();
        emergencyNoTxt = new javax.swing.JTextField();
        heartCheckBox = new javax.swing.JCheckBox();
        liverCheckBox = new javax.swing.JCheckBox();
        kidneyCheckBox = new javax.swing.JCheckBox();
        intestineCheckBox = new javax.swing.JCheckBox();
        pancreasCheckBox = new javax.swing.JCheckBox();
        lungsCheckBox = new javax.swing.JCheckBox();
        agreeCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        updateBtn = new javax.swing.JButton();
        withdrawBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jScrollPane2.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setToolTipText("");

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Medical Id ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 60, 90, 30);

        medicalIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalIdTxtActionPerformed(evt);
            }
        });
        jPanel1.add(medicalIdTxt);
        medicalIdTxt.setBounds(330, 60, 160, 30);

        firstnameLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl.setText("First Name ");
        jPanel1.add(firstnameLbl);
        firstnameLbl.setBounds(150, 110, 90, 30);

        firstnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(firstnameTxt);
        firstnameTxt.setBounds(150, 140, 160, 30);

        lastnameLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lastnameLbl.setText("Last Name ");
        jPanel1.add(lastnameLbl);
        lastnameLbl.setBounds(450, 110, 90, 30);

        lastNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameTxt);
        lastNameTxt.setBounds(450, 140, 160, 30);

        sexLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sexLbl.setText("Gender");
        jPanel1.add(sexLbl);
        sexLbl.setBounds(140, 180, 59, 30);

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(genderComboBox);
        genderComboBox.setBounds(140, 210, 462, 27);

        dobLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        dobLbl.setText("Date Of Birth ");
        jPanel1.add(dobLbl);
        dobLbl.setBounds(140, 250, 123, 30);

        dobTxt.setText("MM-DD-YYYY");
        dobTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTxtActionPerformed(evt);
            }
        });
        jPanel1.add(dobTxt);
        dobTxt.setBounds(150, 280, 457, 30);

        regisLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        regisLbl.setText("Email");
        jPanel1.add(regisLbl);
        regisLbl.setBounds(140, 320, 168, 30);

        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        jPanel1.add(emailTxt);
        emailTxt.setBounds(150, 360, 456, 30);

        regisLbl2.setFont(regisLbl2.getFont().deriveFont((regisLbl2.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, regisLbl2.getFont().getSize()+1));
        regisLbl2.setText("Street Address");
        jPanel1.add(regisLbl2);
        regisLbl2.setBounds(140, 400, 168, 30);

        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        jPanel1.add(addressTxt);
        addressTxt.setBounds(150, 430, 456, 30);

        firstnameLbl3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl3.setText("City");
        jPanel1.add(firstnameLbl3);
        firstnameLbl3.setBounds(140, 470, 90, 30);

        cityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtActionPerformed(evt);
            }
        });
        jPanel1.add(cityTxt);
        cityTxt.setBounds(150, 510, 145, 30);

        firstnameLbl1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl1.setText("State");
        jPanel1.add(firstnameLbl1);
        firstnameLbl1.setBounds(300, 470, 90, 30);

        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(stateComboBox);
        stateComboBox.setBounds(300, 510, 165, 27);

        firstnameLbl2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl2.setText("Zip code");
        jPanel1.add(firstnameLbl2);
        firstnameLbl2.setBounds(480, 470, 90, 30);

        zipTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipTxtActionPerformed(evt);
            }
        });
        jPanel1.add(zipTxt);
        zipTxt.setBounds(480, 510, 129, 30);

        firstnameLbl4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl4.setText("Blood Group");
        jPanel1.add(firstnameLbl4);
        firstnameLbl4.setBounds(630, 120, 90, 30);

        bloodTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTxtActionPerformed(evt);
            }
        });
        jPanel1.add(bloodTxt);
        bloodTxt.setBounds(640, 160, 450, 30);

        firstnameLbl5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl5.setText("Emergency Contact");
        jPanel1.add(firstnameLbl5);
        firstnameLbl5.setBounds(640, 190, 170, 30);

        emergencyContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyContactActionPerformed(evt);
            }
        });
        jPanel1.add(emergencyContact);
        emergencyContact.setBounds(640, 220, 190, 30);

        firstnameLbl6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstnameLbl6.setText("Emergency Contact No");
        firstnameLbl6.setAutoscrolls(true);
        jPanel1.add(firstnameLbl6);
        firstnameLbl6.setBounds(870, 190, 170, 40);

        emergencyNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyNoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(emergencyNoTxt);
        emergencyNoTxt.setBounds(860, 220, 230, 30);

        heartCheckBox.setText("Heart");
        heartCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(heartCheckBox);
        heartCheckBox.setBounds(640, 270, 66, 23);

        liverCheckBox.setText("Liver");
        jPanel1.add(liverCheckBox);
        liverCheckBox.setBounds(770, 270, 62, 23);

        kidneyCheckBox.setText("Both Kidneys");
        jPanel1.add(kidneyCheckBox);
        kidneyCheckBox.setBounds(880, 270, 113, 23);

        intestineCheckBox.setText("Intestines");
        jPanel1.add(intestineCheckBox);
        intestineCheckBox.setBounds(880, 300, 106, 23);

        pancreasCheckBox.setText("Pancreas");
        jPanel1.add(pancreasCheckBox);
        pancreasCheckBox.setBounds(770, 300, 87, 23);

        lungsCheckBox.setText("Both lungs");
        jPanel1.add(lungsCheckBox);
        lungsCheckBox.setBounds(640, 300, 99, 23);

        agreeCheckBox.setText(" AGREE TO THE TERMS AND CONDITIONS");
        agreeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(agreeCheckBox);
        agreeCheckBox.setBounds(640, 340, 291, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("This registration is a binding, legal document of organ donation. \nDonor affirms the information provided is accurate. \nDonor agree upon death to donate all eligible organs and tissues for transplant. \nDonor can remove your registration or specify more detailed donation preferences. ");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);


        updateBtn.setBackground(new java.awt.Color(255, 204, 51));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn);


        withdrawBtn.setBackground(new java.awt.Color(255, 204, 51));
        withdrawBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        withdrawBtn.setText("Withdraw");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });
        jPanel1.add(withdrawBtn);


        backBtn.setBackground(new java.awt.Color(255, 204, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(30, 20, 164, 40);

        registerBtn.setBackground(new java.awt.Color(255, 204, 51));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        add(registerBtn);
        registerBtn.setBounds(30, 60, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);

    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTxtActionPerformed

    private void lastNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void dobTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTxtActionPerformed
  
    }//GEN-LAST:event_dobTxtActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
            // Add the conditions and validations
             if(!(heartCheckBox.isSelected()||liverCheckBox.isSelected()||pancreasCheckBox.isSelected()||intestineCheckBox.isSelected()||kidneyCheckBox.isSelected()||lungsCheckBox.isSelected())){
            JOptionPane.showMessageDialog(null,"Select atleast one organ to donate");
        }
             else{
        OrganDonor od = odd.addOrganDonor();
       SimpleDateFormat ft = new SimpleDateFormat("MM-dd-yyyy");
        Date dob = new Date();
        try {
            dob = ft.parse(dobTxt.getText());
        } catch (ParseException ex) {
            Logger.getLogger(DonorRegistrationJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
   
        od.setFname(firstnameTxt.getText());
        od.setLname(lastNameTxt.getText());
        od.setMedicalID(Integer.parseInt(medicalIdTxt.getText()));
        od.setAddress(addressTxt.getText());
        od.setBloodGrp(bloodTxt.getText());
        od.setCity(cityTxt.getText());
        od.setState((String) stateComboBox.getSelectedItem());
        od.setZip(Integer.parseInt(zipTxt.getText()));
        od.setDob(dob);
        od.setEmailID(emailTxt.getText());
        od.setEmergencyContactName(emergencyContact.getText());
        od.setEmergencyContactNo(Long.parseLong(emergencyNoTxt.getText()));
        od.setGender((String) genderComboBox.getSelectedItem());
        addOrgans(od);
        
        DonorCardJPanel donorCardJPanel = new DonorCardJPanel(userProcessContainer, od);// Add the donor being created
        userProcessContainer.add("DonorCardJPanel", donorCardJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
      }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void cityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtActionPerformed

    private void zipTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipTxtActionPerformed

    private void agreeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeCheckBoxActionPerformed
        // TODO add your handling code here:
        if(agreeCheckBox.isSelected()){
            registerBtn.setVisible(true);
            updateBtn.setVisible(true);
            withdrawBtn.setVisible(true);
        }
        if(!agreeCheckBox.isSelected()){
            registerBtn.setVisible(false);
            updateBtn.setVisible(false);
            withdrawBtn.setVisible(false);
        }
        if(checkAlreadyDonor==1 && agreeCheckBox.isSelected()){
           registerBtn.setVisible(false);
        }
    }//GEN-LAST:event_agreeCheckBoxActionPerformed

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
        // TODO add your handling code here:
         int id = Integer.parseInt(medicalIdTxt.getText());
        for(OrganDonor od : odd.getOrganDonorList()){
           if(id == od.getMedicalID()){
               JOptionPane.showConfirmDialog(null,"Are you sure?");
               int answer = 0;
                 if (answer == JOptionPane.YES_OPTION) {
                       odd.deleteOrganDonor(od);
                       break;
                } else if (answer == JOptionPane.NO_OPTION) {
                    break;
                 }
               
           }
        }
    }//GEN-LAST:event_withdrawBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void emergencyContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyContactActionPerformed

    private void emergencyNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyNoTxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if(!(heartCheckBox.isSelected()||liverCheckBox.isSelected()||pancreasCheckBox.isSelected()||intestineCheckBox.isSelected()||kidneyCheckBox.isSelected()||lungsCheckBox.isSelected())){
            JOptionPane.showMessageDialog(null,"Select atleast one organ to donate");
           
        }else{
        int id = Integer.parseInt(medicalIdTxt.getText());
        for(OrganDonor od : odd.getOrganDonorList()){
           if(id == od.getMedicalID()){
        SimpleDateFormat ft = new SimpleDateFormat("MM-dd-yyyy");
        Date dob = new Date();
        try {
            dob = ft.parse(dobTxt.getText());
        } catch (ParseException ex) {
            Logger.getLogger(DonorRegistrationJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        od.setFname(firstnameTxt.getText());
        od.setLname(lastNameTxt.getText());
        od.setMedicalID(id);
        od.setAddress(addressTxt.getText());
        od.setBloodGrp(bloodTxt.getText());
        od.setCity(cityTxt.getText());
        od.setState((String) stateComboBox.getSelectedItem());
        od.setZip(Integer.parseInt(zipTxt.getText()));
        od.setDob(dob);
        od.setEmailID(emailTxt.getText());
        od.setEmergencyContactName(emergencyContact.getText());
        od.setEmergencyContactNo(Long.parseLong(emergencyNoTxt.getText()));
        od.setGender((String) genderComboBox.getSelectedItem());
        addOrgans(od);
        DonorCardJPanel donorCardJPanel = new DonorCardJPanel(userProcessContainer, od);// Add the donor being created
        userProcessContainer.add("DonorCardJPanel", donorCardJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        break;
           }
       
        }
       
       }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void bloodTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTxtActionPerformed

    private void medicalIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalIdTxtActionPerformed
        // TODO add your handling code here:
        int check=0;
        int mid = Integer.parseInt(medicalIdTxt.getText());

        
          for(MedicalRecord mr : medicalRecords.getMedicalIdList()){

            if(mid== mr.getMedicalId()){
               check=1;
               firstnameTxt.setText(mr.getFirstName());
               lastNameTxt.setText(mr.getLastName());
               genderComboBox.setSelectedItem(mr.getSex());
               dobTxt.setText(mr.getDateOfBirth().toString());
               bloodTxt.setText(mr.getBloodGroup());
               break;
           }    
        for(OrganDonor od : odd.getOrganDonorList()){
            if(od.getMedicalID()== mid){
                registerBtn.setVisible(false);
                checkAlreadyDonor=1;
                firstnameTxt.setText(od.getFname());
                lastNameTxt.setText(od.getLname());
                genderComboBox.setSelectedItem(od.getGender());
                dobTxt.setText(od.getDob().toString());
                bloodTxt.setText(od.getBloodGrp());
                emailTxt.setText(od.getEmailID());
                addressTxt.setText(od.getAddress());
                cityTxt.setText(od.getCity());
                int zip = od.getZip();
                zipTxt.setText(String.valueOf(zip));
                stateComboBox.setSelectedItem(od.getState());
                emergencyContact.setText(od.getEmergencyContactName());
                emergencyNoTxt.setText(String.valueOf(od.getEmergencyContactNo()));
                break;
            }
        }
      
          
        }
         if(check==0){
               JOptionPane.showMessageDialog(null, "Enter a valid Medical ID");
           }
      
    }//GEN-LAST:event_medicalIdTxtActionPerformed

    private void heartCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartCheckBoxActionPerformed
        private void populateGenderComboBox() {
            genderComboBox.removeAllItems();
            String[] sex = {"Male", "Female", "Others" };
            for(String s: sex){
                genderComboBox.addItem(s);
            }
        }

     private void populateStateComboBox() {
         stateComboBox.removeAllItems();
          String[] states= {
        "Alabama", "Alaska", "Arizona", "Arkansas", "California",
        "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
        "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas",
        "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts",
        "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana",
        "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico",
        "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma",
        "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
        "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia",
        "Wisconsin", "Wyoming"
    };
          for(String state: states){
          stateComboBox.addItem(state);
          }
 
     }
   
      private OrganDonor addOrgans(OrganDonor od) {
          ArrayList<String> s= new ArrayList<String>();
          if(heartCheckBox.isSelected()){ s.add("Heart");} 
          if(liverCheckBox.isSelected() ){ 
              s.add("Liver");}
          if(pancreasCheckBox.isSelected()) { s.add("Pancreas");}
          if(intestineCheckBox.isSelected()){ s.add("Intestine");}
          if(kidneyCheckBox.isSelected()){ s.add("L.Kidney"); s.add("R.Kidney");}
          if(lungsCheckBox.isSelected()){ s.add("L.Lung"); s.add("R.Lung");}
          od.setOrgans(s);
          return od;
          
      }
      private void clearFields() {
                medicalIdTxt.setText("");
                firstnameTxt.setText("");
                lastNameTxt.setText("");
                dobTxt.setText("");
                bloodTxt.setText("");
                emailTxt.setText("");
                addressTxt.setText("");
                cityTxt.setText("");
                zipTxt.setText("");
                emergencyContact.setText("");
                emergencyNoTxt.setText("");
             
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JCheckBox agreeCheckBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bloodTxt;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField emergencyContact;
    private javax.swing.JTextField emergencyNoTxt;
    private javax.swing.JLabel firstnameLbl;
    private javax.swing.JLabel firstnameLbl1;
    private javax.swing.JLabel firstnameLbl2;
    private javax.swing.JLabel firstnameLbl3;
    private javax.swing.JLabel firstnameLbl4;
    private javax.swing.JLabel firstnameLbl5;
    private javax.swing.JLabel firstnameLbl6;
    private javax.swing.JTextField firstnameTxt;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JCheckBox heartCheckBox;
    private javax.swing.JCheckBox intestineCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox kidneyCheckBox;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JLabel lastnameLbl;
    private javax.swing.JCheckBox liverCheckBox;
    private javax.swing.JCheckBox lungsCheckBox;
    private javax.swing.JTextField medicalIdTxt;
    private javax.swing.JCheckBox pancreasCheckBox;
    private javax.swing.JLabel regisLbl;
    private javax.swing.JLabel regisLbl2;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel sexLbl;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton withdrawBtn;
    private javax.swing.JTextField zipTxt;
    // End of variables declaration//GEN-END:variables

    

    
   

   
  
}
