/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Address.Address;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.MedicalId.MedicalRecord;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import UserInterface.AddMedicalId.AddMedicalIdWorkAreaJPanel;
import UserInterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;
import Utilities.Validation;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Niranjanii
 */
public class AddEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployeeJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
   // private MedicalRecord medicalId;
    private Enterprise enterprise;
    MedicalRecord medicalId = null;
    public AddEmployeeJPanel(JPanel userProcessContainer,Organization organization,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;

        jLabel4.setVisible(false);
        Yes.setVisible(false);
        No.setVisible(false);
        
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel5.setVisible(false);
        medicalIdTxt.setVisible(false);
        addMedicalId.setVisible(false);
        addJButton.setVisible(false);
        if(enterprise instanceof HospitalEnterprise)
        {
            if(organization instanceof PatientOrganization)
            {
                 medicalId =((HospitalEnterprise)enterprise).getMedicalIdDirec().addMedicalId();
            
                jLabel4.setVisible(true);
                Yes.setVisible(true);
                No.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
            }
            else
            {
                jLabel4.setVisible(false);
                Yes.setVisible(false);
                No.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        firstFlag = new javax.swing.JLabel();
        ageFlag = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        phoneFlag = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        ageTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Yes = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        No = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        medicalIdTxt = new javax.swing.JTextField();
        addMedicalId = new javax.swing.JButton();
        phoneNumTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        lastFlag = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);
        add(firstFlag);
        firstFlag.setBounds(450, 74, 130, 30);
        add(ageFlag);
        ageFlag.setBounds(450, 114, 130, 30);

        firstNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameTxtKeyTyped(evt);
            }
        });
        add(firstNameTxt);
        firstNameTxt.setBounds(310, 70, 140, 30);
        add(phoneFlag);
        phoneFlag.setBounds(830, 110, 130, 30);

        addJButton.setBackground(new java.awt.Color(255, 204, 51));
        addJButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        addJButton.setText("Create Employee");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton);
        addJButton.setBounds(300, 330, 160, 50);

        ageTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageTxtKeyTyped(evt);
            }
        });
        add(ageTxt);
        ageTxt.setBounds(310, 110, 140, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Do you have medical Id ?");
        add(jLabel4);
        jLabel4.setBounds(160, 180, 190, 20);

        buttonGroup1.add(Yes);
        Yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YesMouseClicked(evt);
            }
        });
        add(Yes);
        Yes.setBounds(380, 180, 20, 21);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Yes");
        add(jLabel6);
        jLabel6.setBounds(344, 170, 100, 40);

        buttonGroup1.add(No);
        No.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoMouseClicked(evt);
            }
        });
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        add(No);
        No.setBounds(450, 180, 20, 21);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("No");
        add(jLabel7);
        jLabel7.setBounds(420, 180, 100, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Medical ID:");
        add(jLabel5);
        jLabel5.setBounds(150, 250, 120, 20);

        medicalIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                medicalIdTxtKeyTyped(evt);
            }
        });
        add(medicalIdTxt);
        medicalIdTxt.setBounds(320, 240, 120, 30);

        addMedicalId.setBackground(new java.awt.Color(255, 204, 51));
        addMedicalId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        addMedicalId.setText("Add Medical Id");
        addMedicalId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicalIdActionPerformed(evt);
            }
        });
        add(addMedicalId);
        addMedicalId.setBounds(280, 240, 210, 40);

        phoneNumTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumTxtKeyTyped(evt);
            }
        });
        add(phoneNumTxt);
        phoneNumTxt.setBounds(690, 110, 130, 30);

        lastNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameTxtKeyTyped(evt);
            }
        });
        add(lastNameTxt);
        lastNameTxt.setBounds(690, 60, 130, 30);
        add(lastFlag);
        lastFlag.setBounds(840, 60, 130, 30);

        backBtn.setBackground(new java.awt.Color(255, 204, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(40, 20, 96, 29);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("First Name :");
        add(jLabel3);
        jLabel3.setBounds(100, 80, 140, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Age :");
        add(jLabel11);
        jLabel11.setBounds(96, 110, 90, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Last Name :");
        add(jLabel12);
        jLabel12.setBounds(560, 70, 130, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setText("Phone Number:");
        add(jLabel13);
        jLabel13.setBounds(550, 110, 140, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-30, 0, 1800, 1150);
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        Address ad= new Address();
        
        
     
        if(organization instanceof PatientOrganization)
        {
               if(!(Validation.nullPointerException(firstNameTxt) && Validation.nullPointerException(lastNameTxt) && Validation.nullPointerException(ageTxt) && Validation.nullPointerException(phoneNumTxt)))
              {
                  
                     ((PatientOrganization)organization).getPatientDirec().addPatient(firstNameTxt.getText(),lastNameTxt.getText(),ageTxt.getText(),phoneNumTxt.getText(),ad,medicalId);
                  
              }
               else
               {
                   JOptionPane.showMessageDialog(null, "Please enter all the values");
               }
        }
        else
        {
             if(!(Validation.nullPointerException(firstNameTxt) && Validation.nullPointerException(lastNameTxt) && Validation.nullPointerException(ageTxt) && Validation.nullPointerException(phoneNumTxt)))
              {
                    organization.getEmployeeDirectory().createEmployee(firstNameTxt.getText(),lastNameTxt.getText(),ageTxt.getText(),phoneNumTxt.getText(),ad);
              }
        }
             userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageEmployeeJPanel manageJPanel = (ManageEmployeeJPanel) component;
        manageJPanel.populateTable(organization);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_addJButtonActionPerformed

    private void YesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesMouseClicked
        jLabel5.setVisible(true);
        medicalIdTxt.setVisible(true);
        addMedicalId.setVisible(false);
    }//GEN-LAST:event_YesMouseClicked

    private void NoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoMouseClicked
        jLabel5.setVisible(false);
        medicalIdTxt.setVisible(false);
        addMedicalId.setVisible(true);
    }//GEN-LAST:event_NoMouseClicked

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoActionPerformed

    private void addMedicalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicalIdActionPerformed
           
        addJButton.setVisible(true);
        
        if(enterprise instanceof HospitalEnterprise)
            {
                 
                AddMedicalIdWorkAreaJPanel addMedicalIdWorkAreaJPanel = new AddMedicalIdWorkAreaJPanel(userProcessContainer,enterprise,medicalId);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                userProcessContainer.add("RequestLabTestJPanel", addMedicalIdWorkAreaJPanel);
                layout.next(userProcessContainer);
            }
    }//GEN-LAST:event_addMedicalIdActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void medicalIdTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medicalIdTxtKeyTyped
        addJButton.setVisible(true);
    }//GEN-LAST:event_medicalIdTxtKeyTyped

    private void firstNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameTxtKeyTyped
          char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_firstNameTxtKeyTyped

    private void lastNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameTxtKeyTyped
           char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_lastNameTxtKeyTyped

    private void ageTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTxtKeyTyped
           char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_ageTxtKeyTyped

    private void phoneNumTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumTxtKeyTyped
           char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_phoneNumTxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton No;
    private javax.swing.JRadioButton Yes;
    private javax.swing.JButton addJButton;
    private javax.swing.JButton addMedicalId;
    private javax.swing.JLabel ageFlag;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel firstFlag;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lastFlag;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField medicalIdTxt;
    private javax.swing.JLabel phoneFlag;
    private javax.swing.JTextField phoneNumTxt;
    // End of variables declaration//GEN-END:variables
}
