/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole.MedicalRecordsDetails;

import Business.MeldTest.MeldTest;
import Business.Patient.Patient;
import Utilities.Validation;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;

/**
 *
 * @author Niranjanii
 */
public class MeldForm extends javax.swing.JPanel {

    /**
     * Creates new form MeldForm
     */
     private JPanel userProcessContainer;
    private Patient patient;
    private boolean meldFlag;
    public MeldForm(JPanel userProcessContainer,Patient patient,boolean meldFlag) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.meldFlag = meldFlag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bilirubinTxt = new javax.swing.JTextField();
        inrTxt = new javax.swing.JTextField();
        creatinineTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);
        add(jLabel3);
        jLabel3.setBounds(250, 250, 0, 0);

        jLabel4.setText("Bilirubin :");
        add(jLabel4);
        jLabel4.setBounds(250, 250, 70, 14);

        jLabel6.setText("INR :");
        add(jLabel6);
        jLabel6.setBounds(260, 290, 25, 14);

        bilirubinTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bilirubinTxtKeyTyped(evt);
            }
        });
        add(bilirubinTxt);
        bilirubinTxt.setBounds(310, 250, 130, 30);

        inrTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inrTxtKeyTyped(evt);
            }
        });
        add(inrTxt);
        inrTxt.setBounds(310, 290, 130, 30);

        creatinineTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                creatinineTxtKeyTyped(evt);
            }
        });
        add(creatinineTxt);
        creatinineTxt.setBounds(310, 210, 130, 30);

        jLabel5.setText("mg/dL");
        add(jLabel5);
        jLabel5.setBounds(450, 210, 70, 20);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(310, 360, 140, 40);

        jLabel7.setText("mg/dL");
        add(jLabel7);
        jLabel7.setBounds(450, 250, 70, 20);

        jLabel8.setText("Creatinine :");
        add(jLabel8);
        jLabel8.setBounds(240, 210, 70, 20);

        backBtn.setBackground(new java.awt.Color(255, 204, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(6, 6, 164, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -10, 1410, 780);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         if(!Validation.nullPointerException(bilirubinTxt) &&  !Validation.nullPointerException(creatinineTxt) &&
                !Validation.nullPointerException(inrTxt)  
                )
        {  
                MeldTest meldTest = patient.getMedicalRecord().getMeldTestDir().addMeldTest();
                meldTest.setBilirubinTxt(Double.parseDouble(bilirubinTxt.getText()));
                meldTest.setCreatinineTxt(Double.parseDouble(creatinineTxt.getText()));
                meldTest.setInrTxt(Double.parseDouble(inrTxt.getText()));
                double meldResult = 10 * ((0.957 * Math.log(meldTest.getCreatinineTxt())) + (0.378 * Math.log(meldTest.getBilirubinTxt())) + (1.12 * Math.log(meldTest.getInrTxt()))) + 6.43;
                meldTest.setMeldResult(Integer.parseInt(String.valueOf(meldResult)));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void creatinineTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creatinineTxtKeyTyped
        	     char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_creatinineTxtKeyTyped

    private void bilirubinTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bilirubinTxtKeyTyped
          	     char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_bilirubinTxtKeyTyped

    private void inrTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inrTxtKeyTyped
          	     char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_inrTxtKeyTyped

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bilirubinTxt;
    private javax.swing.JTextField creatinineTxt;
    private javax.swing.JTextField inrTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
