/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.Address.Address;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import Utilities.Validation;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akshayasuresh
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
     private JPanel userProcessContainer;
    private EcoSystem system;
    private JLabel selectedNodeJLabel;

    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system,JLabel selectedNodeJLabel) {
        initComponents();
        
       this.userProcessContainer = userProcessContainer;
       this.system = system;
       this.selectedNodeJLabel = selectedNodeJLabel; 

        ageFlag.setVisible(false);
        firstNameTxt.setVisible(false);
        lastNameLbl.setVisible(false);
        lastNameTxt.setVisible(false);
        ageLbl.setVisible(false);
        ageTxt.setVisible(false);
        phoneNumLbl.setVisible(false);
        phoneNumTxt.setVisible(false);
        userNameLbl.setVisible(false);
        usernameJTextField.setVisible(false);
        passwordLbl.setVisible(false);
        passwordJPasswordField.setVisible(false);
        submitJButton.setVisible(false);

        populateTable();
        populateNetworkComboBox();
    }

    
     private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
          if(network.getName().equals(selectedNodeJLabel.getText())) {
            
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                   for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                        Object[] row = new Object[5];
                        row[0] = enterprise.getName();
                        row[1] = network.getName();
                        row[2] = userAccount.getUsername();
                        row[3] = userAccount.getEmployee().getFirstName();
                        row[4] = userAccount.getEmployee().getLastName();
                        model.addRow(row);
                    }
                }
          }
        }
    }

    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : system.getNetworkList()){
           /* if(network.getName().equals(selectedNodeJLabel.getText())) */
            
            networkJComboBox.addItem(network);
            
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        enterpriseJComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            enterpriseJComboBox.addItem(enterprise);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        userNameLbl = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        ageFlag = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        lastNameLbl = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        phoneNumLbl = new javax.swing.JLabel();
        phoneNumTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        firstNameFlag = new javax.swing.JLabel();
        userNameFLag = new javax.swing.JLabel();
        firstNameLbl2 = new javax.swing.JLabel();
        firstNameFlag1 = new javax.swing.JLabel();
        passwordFlag = new javax.swing.JLabel();
        phoneFlag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);

        enterpriseJTable.setBackground(new java.awt.Color(0, 0, 0));
        enterpriseJTable.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        enterpriseJTable.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Username", "FirstName", "LastName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(240, 40, 523, 95);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Network :");
        add(jLabel2);
        jLabel2.setBounds(350, 160, 80, 20);

        networkJComboBox.setBackground(new java.awt.Color(0, 0, 0));
        networkJComboBox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        networkJComboBox.setForeground(new java.awt.Color(255, 255, 255));
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox);
        networkJComboBox.setBounds(470, 150, 140, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Enterprise :");
        add(jLabel3);
        jLabel3.setBounds(350, 200, 80, 30);

        enterpriseJComboBox.setBackground(new java.awt.Color(0, 0, 0));
        enterpriseJComboBox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        enterpriseJComboBox.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseJComboBox);
        enterpriseJComboBox.setBounds(470, 200, 140, 30);

        userNameLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        userNameLbl.setText("Username :");
        add(userNameLbl);
        userNameLbl.setBounds(160, 430, 90, 20);

        usernameJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameJTextFieldKeyTyped(evt);
            }
        });
        add(usernameJTextField);
        usernameJTextField.setBounds(280, 420, 130, 30);

        passwordLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        passwordLbl.setText("Password :");
        add(passwordLbl);
        passwordLbl.setBounds(600, 420, 80, 20);

        passwordJPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordJPasswordFieldKeyTyped(evt);
            }
        });
        add(passwordJPasswordField);
        passwordJPasswordField.setBounds(720, 410, 140, 30);

        backJButton.setBackground(new java.awt.Color(255, 204, 51));
        backJButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(100, 30, 110, 30);

        submitJButton.setBackground(new java.awt.Color(255, 204, 51));
        submitJButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(510, 460, 110, 30);

        ageFlag.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        add(ageFlag);
        ageFlag.setBounds(490, 370, 110, 0);

        ageLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ageLbl.setText("Age :");
        add(ageLbl);
        ageLbl.setBounds(160, 380, 60, 20);

        firstNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameTxtKeyTyped(evt);
            }
        });
        add(firstNameTxt);
        firstNameTxt.setBounds(280, 320, 130, 30);

        ageTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageTxtKeyTyped(evt);
            }
        });
        add(ageTxt);
        ageTxt.setBounds(280, 370, 130, 30);

        lastNameLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lastNameLbl.setText("Last Name :");
        add(lastNameLbl);
        lastNameLbl.setBounds(600, 330, 100, 20);

        lastNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameTxtKeyTyped(evt);
            }
        });
        add(lastNameTxt);
        lastNameTxt.setBounds(720, 320, 140, 30);

        phoneNumLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        phoneNumLbl.setText("Phone Number :");
        add(phoneNumLbl);
        phoneNumLbl.setBounds(600, 370, 110, 20);

        phoneNumTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumTxtKeyTyped(evt);
            }
        });
        add(phoneNumTxt);
        phoneNumTxt.setBounds(720, 370, 140, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Add Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(620, 200, 150, 30);

        firstNameFlag.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        add(firstNameFlag);
        firstNameFlag.setBounds(870, 320, 140, 30);

        userNameFLag.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        add(userNameFLag);
        userNameFLag.setBounds(440, 420, 140, 30);

        firstNameLbl2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        firstNameLbl2.setText("First Name :");
        add(firstNameLbl2);
        firstNameLbl2.setBounds(160, 330, 110, 20);

        firstNameFlag1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        add(firstNameFlag1);
        firstNameFlag1.setBounds(430, 320, 170, 30);

        passwordFlag.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        add(passwordFlag);
        passwordFlag.setBounds(880, 410, 130, 30);

        phoneFlag.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        add(phoneFlag);
        phoneFlag.setBounds(870, 370, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -10, 1410, 780);
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        
        
        
        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
        Employee employee = null;
        String username = usernameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        
        Address ad = new Address();
        if(!Validation.nullPointerException(firstNameTxt) && !Validation.nullPointerException(lastNameTxt))
        {
          
              employee = enterprise.getEmployeeDirectory().createEmployee(firstNameTxt.getText(),lastNameTxt.getText(),ageTxt.getText(),phoneNumTxt.getText(),ad);
             
                UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password,employee, new AdminRole());

                populateTable();
            
            
             
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Enter all the Values");
        }
        
                 
         

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(networkJComboBox.getSelectedItem()!=null && enterpriseJComboBox.getSelectedItem()!=null)
        {
               
            ageFlag.setVisible(true);
            firstNameTxt.setVisible(true);
            lastNameLbl.setVisible(true);
            lastNameTxt.setVisible(true);
            ageLbl.setVisible(true);
            ageTxt.setVisible(true);
            phoneNumLbl.setVisible(true);
            phoneNumTxt.setVisible(true);
            userNameLbl.setVisible(true);
            usernameJTextField.setVisible(true);
            passwordLbl.setVisible(true);
            passwordJPasswordField.setVisible(true);
            submitJButton.setVisible(true);

        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select both networka and enterprise to add employee");
        }
        
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ageTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTxtKeyTyped
       char vchar = evt.getKeyChar();
       if(! (Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_ageTxtKeyTyped

    private void firstNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameTxtKeyTyped
         char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_firstNameTxtKeyTyped

    private void lastNameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameTxtKeyTyped
           char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_lastNameTxtKeyTyped

    private void phoneNumTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumTxtKeyTyped
           char vchar = evt.getKeyChar();
       if(! (Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_phoneNumTxtKeyTyped

    private void usernameJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameJTextFieldKeyTyped
           char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_usernameJTextFieldKeyTyped

    private void passwordJPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordJPasswordFieldKeyTyped
           char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_passwordJPasswordFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageFlag;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel firstNameFlag;
    private javax.swing.JLabel firstNameFlag1;
    private javax.swing.JLabel firstNameLbl2;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JLabel passwordFlag;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel phoneFlag;
    private javax.swing.JLabel phoneNumLbl;
    private javax.swing.JTextField phoneNumTxt;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel userNameFLag;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
