/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole.MedicalRecordsDetails;

import Business.BloodTest.BloodTest;
import Business.Patient.Patient;
import UserInterface.LabAssistant.ProcessRequestJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Niranjanii
 */

public class BloodTestReport extends javax.swing.JPanel {

    /**
     * Creates new form BloodTestReport
     */
    private JPanel userProcessContainer;
    private Patient patient;
    private boolean bloodFlag;
    public BloodTestReport(JPanel userProcessContainer,Patient patient,boolean bloodFlag) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.patient=patient;
        this.bloodFlag = bloodFlag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        specTxt = new javax.swing.JTextField();
        specimenTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        collectedDate = new javax.swing.JTextField();
        collectedTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        receivedDate = new javax.swing.JTextField();
        receivedTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        queriesTxt = new javax.swing.JTextField();
        orderedTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        sexTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        physicianCopyTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        statusTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dobTxt = new javax.swing.JTextField();
        orderingDrTxt = new javax.swing.JTextField();
        patientTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        hbNormal = new javax.swing.JTextField();
        wbcAbnorm = new javax.swing.JTextField();
        hctNormal = new javax.swing.JTextField();
        mcvNormal = new javax.swing.JTextField();
        mchNormal = new javax.swing.JTextField();
        mchcNormal = new javax.swing.JTextField();
        rdwNormal = new javax.swing.JTextField();
        platecountNormal = new javax.swing.JTextField();
        meanPlateNormal = new javax.swing.JTextField();
        rbcnormal = new javax.swing.JTextField();
        tbcAbNorm = new javax.swing.JTextField();
        mchAbNorm = new javax.swing.JTextField();
        hctAbNorm = new javax.swing.JTextField();
        mcvAbNorm = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        mchcAbNorm = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        hbAbnorm = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        rbcflg = new javax.swing.JTextField();
        hbflg = new javax.swing.JTextField();
        hctflg = new javax.swing.JTextField();
        mcvflg = new javax.swing.JTextField();
        mchcflg = new javax.swing.JTextField();
        wbcNormal = new javax.swing.JTextField();
        rdwflg = new javax.swing.JTextField();
        meanplateflg = new javax.swing.JTextField();
        mchflg = new javax.swing.JTextField();
        plateletflg = new javax.swing.JTextField();
        wbcflg = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 102));
        setAutoscrolls(true);
        setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setOpaque(false);
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setText("Specimen :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 80, 110, 30);

        specTxt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(specTxt);
        specTxt.setBounds(120, 40, 140, 30);

        specimenTxt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(specimenTxt);
        specimenTxt.setBounds(120, 80, 140, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setText("Collected Date :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(280, 40, 130, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setText("Ordered :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(880, 80, 100, 30);

        collectedDate.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(collectedDate);
        collectedDate.setBounds(420, 40, 150, 30);

        collectedTime.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(collectedTime);
        collectedTime.setBounds(420, 80, 150, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Received Date :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(600, 40, 98, 20);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel17.setText("Queries :");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(880, 40, 120, 20);

        receivedDate.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(receivedDate);
        receivedDate.setBounds(710, 40, 150, 30);

        receivedTime.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(receivedTime);
        receivedTime.setBounds(710, 80, 150, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Spec # :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 40, 80, 20);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel18.setText("Collected Time :");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(280, 90, 110, 20);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel19.setText("Received Time :");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(600, 90, 150, 20);

        queriesTxt.setBackground(new java.awt.Color(255, 255, 204));
        queriesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queriesTxtActionPerformed(evt);
            }
        });
        jPanel2.add(queriesTxt);
        queriesTxt.setBounds(950, 40, 150, 30);

        orderedTxt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(orderedTxt);
        orderedTxt.setBounds(950, 80, 150, 30);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(40, 180, 1180, 120);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Sex :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(260, 80, 100, 30);

        sexTxt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(sexTxt);
        sexTxt.setBounds(330, 80, 150, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Physician Copy for : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(820, 80, 150, 20);

        physicianCopyTxt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(physicianCopyTxt);
        physicianCopyTxt.setBounds(950, 80, 150, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Status :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(830, 40, 90, 20);

        statusTxt.setBackground(new java.awt.Color(255, 255, 204));
        statusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTxtActionPerformed(evt);
            }
        });
        jPanel1.add(statusTxt);
        statusTxt.setBounds(950, 40, 150, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("DOB :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(510, 40, 80, 20);

        dobTxt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(dobTxt);
        dobTxt.setBounds(620, 40, 150, 30);

        orderingDrTxt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(orderingDrTxt);
        orderingDrTxt.setBounds(620, 80, 150, 30);

        patientTxt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(patientTxt);
        patientTxt.setBounds(100, 80, 140, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Ordering Dr : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(510, 80, 120, 20);

        nameTxt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(nameTxt);
        nameTxt.setBounds(100, 40, 140, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 80, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Age :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(260, 40, 100, 30);

        ageTxt.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(ageTxt);
        ageTxt.setBounds(330, 40, 150, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setText("Patient Id :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 80, 110, 30);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(40, 50, 1180, 120);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Doctor Name :");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(450, 0, 130, 40);

        jTextField4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.add(jTextField4);
        jTextField4.setBounds(280, 10, 140, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Report Date :");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(720, 10, 100, 30);

        jTextField8.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.add(jTextField8);
        jTextField8.setBounds(820, 10, 150, 30);

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(530, 1020, 120, 30);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel20.setText("Abnormal :");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(410, 40, 80, 20);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel21.setText("White Blood Cell (WBC)");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(10, 120, 160, 20);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel22.setText("Reference Range :");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(950, 40, 120, 20);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel23.setText("Normal :");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(220, 40, 80, 20);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel24.setText("Flag :");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(580, 30, 80, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel25.setText("g/dL");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(760, 300, 80, 20);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel26.setText("Test :");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(40, 40, 80, 20);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel27.setText("Red Blood Cell (RBC)");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(10, 150, 160, 20);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel28.setText("Hemoglobin (HB/Hgb)");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(10, 180, 160, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel29.setText("Hematocrit (HCT)");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(10, 210, 160, 20);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel30.setText("Mean Call Volume (MCV)");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(10, 240, 180, 20);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel31.setText("Mean Cell Hb Conc(MCHC)");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(10, 300, 200, 20);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel32.setText("Complete Blood Count :");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(10, 90, 160, 20);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel33.setText("Platelet count ");
        jPanel3.add(jLabel33);
        jLabel33.setBounds(10, 360, 200, 20);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel34.setText("Mean Cell Hemoglobin (MCH)");
        jPanel3.add(jLabel34);
        jLabel34.setBounds(10, 270, 200, 20);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel35.setText("Mean Platelet Volume");
        jPanel3.add(jLabel35);
        jLabel35.setBounds(10, 390, 200, 20);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel36.setText("Red Cell Dist Width (RDW)");
        jPanel3.add(jLabel36);
        jLabel36.setBounds(10, 330, 200, 20);

        hbNormal.setBackground(new java.awt.Color(255, 255, 204));
        hbNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbNormalActionPerformed(evt);
            }
        });
        jPanel3.add(hbNormal);
        hbNormal.setBounds(220, 180, 60, 20);

        wbcAbnorm.setBackground(new java.awt.Color(255, 255, 204));
        wbcAbnorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wbcAbnormActionPerformed(evt);
            }
        });
        jPanel3.add(wbcAbnorm);
        wbcAbnorm.setBounds(410, 120, 60, 20);

        hctNormal.setBackground(new java.awt.Color(255, 255, 204));
        hctNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hctNormalActionPerformed(evt);
            }
        });
        jPanel3.add(hctNormal);
        hctNormal.setBounds(220, 210, 60, 20);

        mcvNormal.setBackground(new java.awt.Color(255, 255, 204));
        mcvNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcvNormalActionPerformed(evt);
            }
        });
        jPanel3.add(mcvNormal);
        mcvNormal.setBounds(220, 240, 60, 20);

        mchNormal.setBackground(new java.awt.Color(255, 255, 204));
        mchNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mchNormalActionPerformed(evt);
            }
        });
        jPanel3.add(mchNormal);
        mchNormal.setBounds(220, 270, 60, 20);

        mchcNormal.setBackground(new java.awt.Color(255, 255, 204));
        mchcNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mchcNormalActionPerformed(evt);
            }
        });
        jPanel3.add(mchcNormal);
        mchcNormal.setBounds(220, 300, 60, 20);

        rdwNormal.setBackground(new java.awt.Color(255, 255, 204));
        rdwNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdwNormalActionPerformed(evt);
            }
        });
        jPanel3.add(rdwNormal);
        rdwNormal.setBounds(220, 330, 60, 20);

        platecountNormal.setBackground(new java.awt.Color(255, 255, 204));
        platecountNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platecountNormalActionPerformed(evt);
            }
        });
        jPanel3.add(platecountNormal);
        platecountNormal.setBounds(220, 360, 60, 20);

        meanPlateNormal.setBackground(new java.awt.Color(255, 255, 204));
        meanPlateNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meanPlateNormalActionPerformed(evt);
            }
        });
        jPanel3.add(meanPlateNormal);
        meanPlateNormal.setBounds(220, 390, 60, 20);

        rbcnormal.setBackground(new java.awt.Color(255, 255, 204));
        rbcnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcnormalActionPerformed(evt);
            }
        });
        jPanel3.add(rbcnormal);
        rbcnormal.setBounds(220, 150, 60, 20);

        tbcAbNorm.setBackground(new java.awt.Color(255, 255, 204));
        tbcAbNorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbcAbNormActionPerformed(evt);
            }
        });
        jPanel3.add(tbcAbNorm);
        tbcAbNorm.setBounds(410, 150, 60, 20);

        mchAbNorm.setBackground(new java.awt.Color(255, 255, 204));
        mchAbNorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mchAbNormActionPerformed(evt);
            }
        });
        jPanel3.add(mchAbNorm);
        mchAbNorm.setBounds(410, 270, 60, 20);

        hctAbNorm.setBackground(new java.awt.Color(255, 255, 204));
        hctAbNorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hctAbNormActionPerformed(evt);
            }
        });
        jPanel3.add(hctAbNorm);
        hctAbNorm.setBounds(410, 210, 60, 20);

        mcvAbNorm.setBackground(new java.awt.Color(255, 255, 204));
        mcvAbNorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcvAbNormActionPerformed(evt);
            }
        });
        jPanel3.add(mcvAbNorm);
        mcvAbNorm.setBounds(410, 240, 60, 20);

        jTextField35.setBackground(new java.awt.Color(255, 255, 204));
        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField35);
        jTextField35.setBounds(410, 360, 60, 20);

        mchcAbNorm.setBackground(new java.awt.Color(255, 255, 204));
        mchcAbNorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mchcAbNormActionPerformed(evt);
            }
        });
        jPanel3.add(mchcAbNorm);
        mchcAbNorm.setBounds(410, 300, 60, 20);

        jTextField37.setBackground(new java.awt.Color(255, 255, 204));
        jTextField37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField37ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField37);
        jTextField37.setBounds(410, 330, 60, 20);

        hbAbnorm.setBackground(new java.awt.Color(255, 255, 204));
        hbAbnorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbAbnormActionPerformed(evt);
            }
        });
        jPanel3.add(hbAbnorm);
        hbAbnorm.setBounds(410, 180, 60, 20);

        jTextField39.setBackground(new java.awt.Color(255, 255, 204));
        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField39);
        jTextField39.setBounds(410, 390, 60, 20);

        rbcflg.setBackground(new java.awt.Color(255, 255, 204));
        rbcflg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcflgActionPerformed(evt);
            }
        });
        jPanel3.add(rbcflg);
        rbcflg.setBounds(570, 150, 60, 20);

        hbflg.setBackground(new java.awt.Color(255, 255, 204));
        hbflg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbflgActionPerformed(evt);
            }
        });
        jPanel3.add(hbflg);
        hbflg.setBounds(570, 180, 60, 20);

        hctflg.setBackground(new java.awt.Color(255, 255, 204));
        hctflg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hctflgActionPerformed(evt);
            }
        });
        jPanel3.add(hctflg);
        hctflg.setBounds(570, 210, 60, 20);

        mcvflg.setBackground(new java.awt.Color(255, 255, 204));
        mcvflg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcvflgActionPerformed(evt);
            }
        });
        jPanel3.add(mcvflg);
        mcvflg.setBounds(570, 240, 60, 20);

        mchcflg.setBackground(new java.awt.Color(255, 255, 204));
        mchcflg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mchcflgActionPerformed(evt);
            }
        });
        jPanel3.add(mchcflg);
        mchcflg.setBounds(570, 300, 60, 20);

        wbcNormal.setBackground(new java.awt.Color(255, 255, 204));
        wbcNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wbcNormalActionPerformed(evt);
            }
        });
        jPanel3.add(wbcNormal);
        wbcNormal.setBounds(220, 120, 60, 20);

        rdwflg.setBackground(new java.awt.Color(255, 255, 204));
        rdwflg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdwflgActionPerformed(evt);
            }
        });
        jPanel3.add(rdwflg);
        rdwflg.setBounds(570, 330, 60, 20);

        meanplateflg.setBackground(new java.awt.Color(255, 255, 204));
        meanplateflg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meanplateflgActionPerformed(evt);
            }
        });
        jPanel3.add(meanplateflg);
        meanplateflg.setBounds(570, 390, 60, 20);

        mchflg.setBackground(new java.awt.Color(255, 255, 204));
        mchflg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mchflgActionPerformed(evt);
            }
        });
        jPanel3.add(mchflg);
        mchflg.setBounds(570, 270, 60, 20);

        plateletflg.setBackground(new java.awt.Color(255, 255, 204));
        plateletflg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateletflgActionPerformed(evt);
            }
        });
        jPanel3.add(plateletflg);
        plateletflg.setBounds(570, 360, 60, 20);

        wbcflg.setBackground(new java.awt.Color(255, 255, 204));
        wbcflg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wbcflgActionPerformed(evt);
            }
        });
        jPanel3.add(wbcflg);
        wbcflg.setBounds(570, 120, 60, 20);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel37.setText("M/mcL");
        jPanel3.add(jLabel37);
        jLabel37.setBounds(760, 150, 80, 20);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel38.setText("g/dL");
        jPanel3.add(jLabel38);
        jLabel38.setBounds(760, 180, 80, 20);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel39.setText("%");
        jPanel3.add(jLabel39);
        jLabel39.setBounds(760, 210, 80, 20);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel40.setText("fL");
        jPanel3.add(jLabel40);
        jLabel40.setBounds(760, 240, 80, 20);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel41.setText("fL");
        jPanel3.add(jLabel41);
        jLabel41.setBounds(760, 390, 80, 20);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel42.setText("Units :");
        jPanel3.add(jLabel42);
        jLabel42.setBounds(760, 40, 80, 20);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel43.setText("4.8 - 10.8");
        jPanel3.add(jLabel43);
        jLabel43.setBounds(960, 120, 80, 20);

        jLabel45.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel45.setText("pg");
        jPanel3.add(jLabel45);
        jLabel45.setBounds(760, 270, 80, 20);

        jLabel46.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel46.setText("%");
        jPanel3.add(jLabel46);
        jLabel46.setBounds(760, 330, 80, 20);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel47.setText("K/mCL");
        jPanel3.add(jLabel47);
        jLabel47.setBounds(760, 360, 80, 20);

        jLabel48.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel48.setText("4.7 - 6.1");
        jPanel3.add(jLabel48);
        jLabel48.setBounds(960, 150, 80, 20);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel49.setText("42 - 52");
        jPanel3.add(jLabel49);
        jLabel49.setBounds(960, 210, 80, 20);

        jLabel50.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel50.setText("K/mCL");
        jPanel3.add(jLabel50);
        jLabel50.setBounds(760, 120, 80, 20);

        jLabel51.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel51.setText("80 - 100");
        jPanel3.add(jLabel51);
        jLabel51.setBounds(960, 240, 80, 20);

        jLabel52.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel52.setText("11.5 - 14.5");
        jPanel3.add(jLabel52);
        jLabel52.setBounds(960, 330, 80, 20);

        jLabel53.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel53.setText("14.0 - 18.0");
        jPanel3.add(jLabel53);
        jLabel53.setBounds(960, 180, 80, 20);

        jLabel54.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel54.setText("27.0 - 32.0");
        jPanel3.add(jLabel54);
        jLabel54.setBounds(960, 270, 80, 20);

        jLabel55.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel55.setText("7.5 - 11.0");
        jPanel3.add(jLabel55);
        jLabel55.setBounds(960, 390, 80, 20);

        jLabel56.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel56.setText("32.0 - 36.0");
        jPanel3.add(jLabel56);
        jLabel56.setBounds(960, 300, 80, 20);

        jLabel57.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel57.setText("150 - 450");
        jPanel3.add(jLabel57);
        jLabel57.setBounds(960, 360, 80, 20);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        jPanel3.add(jLabel44);
        jLabel44.setBounds(0, 4, 1180, 350);

        jScrollPane2.setViewportView(jPanel3);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(40, 310, 1180, 380);

        jLabel58.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel58.setText("Hospital Name :");
        jPanel4.add(jLabel58);
        jLabel58.setBounds(170, 0, 130, 40);

        jButton2.setBackground(new java.awt.Color(255, 204, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(420, 710, 120, 40);

        jTextField5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.add(jTextField5);
        jTextField5.setBounds(550, 10, 140, 30);

        add(jPanel4);
        jPanel4.setBounds(-30, 20, 1770, 1260);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BloodTest b=patient.getMedicalRecord().getBloodtestDir().addBloodTest();
        //       b.setCollectionDate(collectionDate);
        //       b.setCollectiontime(collectiontime);
        //       b.setHb(TOP_ALIGNMENT);
        //       b.setHct(TOP_ALIGNMENT);
        //       b.setMch(TOP_ALIGNMENT);
        //       b.setMchc(TOP_ALIGNMENT);
        //       b.setMcv(TOP_ALIGNMENT);
        //       b.setMeanPlatelet(TOP_ALIGNMENT);
        //       b.setOrdered(TOOL_TIP_TEXT_KEY);
        //       b.setOrderingDr(TOOL_TIP_TEXT_KEY);
        //       b.setPhysicianCopy(TOOL_TIP_TEXT_KEY);
        //       b.setPlateletCount(TOP_ALIGNMENT);
        //       b.setQueries(TOOL_TIP_TEXT_KEY);
        //       b.setRbc(TOP_ALIGNMENT);
        //       b.setRdw(TOP_ALIGNMENT);
        //       b.setReceivedDate(receivedDate);
        //       b.setRecivedTime(RecivedTime);
        //       b.setSpec(WIDTH);
        //       b.setSpecimen(TOOL_TIP_TEXT_KEY);
        //       b.setStatus(TOOL_TIP_TEXT_KEY);
        //       b.setWbc(TOP_ALIGNMENT);

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProcessRequestJPanel sysAdminwjp = (ProcessRequestJPanel) component;
        sysAdminwjp.populateCombobox();
        bloodFlag =true;

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void wbcflgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wbcflgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wbcflgActionPerformed

    private void plateletflgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateletflgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateletflgActionPerformed

    private void mchflgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mchflgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mchflgActionPerformed

    private void meanplateflgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meanplateflgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meanplateflgActionPerformed

    private void rdwflgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdwflgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdwflgActionPerformed

    private void wbcNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wbcNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wbcNormalActionPerformed

    private void mchcflgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mchcflgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mchcflgActionPerformed

    private void mcvflgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcvflgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcvflgActionPerformed

    private void hctflgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hctflgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hctflgActionPerformed

    private void hbflgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbflgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hbflgActionPerformed

    private void rbcflgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcflgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcflgActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void hbAbnormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbAbnormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hbAbnormActionPerformed

    private void jTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37ActionPerformed

    private void mchcAbNormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mchcAbNormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mchcAbNormActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void mcvAbNormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcvAbNormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcvAbNormActionPerformed

    private void hctAbNormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hctAbNormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hctAbNormActionPerformed

    private void mchAbNormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mchAbNormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mchAbNormActionPerformed

    private void tbcAbNormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbcAbNormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbcAbNormActionPerformed

    private void rbcnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcnormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcnormalActionPerformed

    private void meanPlateNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meanPlateNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meanPlateNormalActionPerformed

    private void platecountNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platecountNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platecountNormalActionPerformed

    private void rdwNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdwNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdwNormalActionPerformed

    private void mchcNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mchcNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mchcNormalActionPerformed

    private void mchNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mchNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mchNormalActionPerformed

    private void mcvNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcvNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcvNormalActionPerformed

    private void hctNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hctNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hctNormalActionPerformed

    private void wbcAbnormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wbcAbnormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wbcAbnormActionPerformed

    private void hbNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hbNormalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void statusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTxtActionPerformed

    private void queriesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queriesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queriesTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt;
    private javax.swing.JTextField collectedDate;
    private javax.swing.JTextField collectedTime;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JTextField hbAbnorm;
    private javax.swing.JTextField hbNormal;
    private javax.swing.JTextField hbflg;
    private javax.swing.JTextField hctAbNorm;
    private javax.swing.JTextField hctNormal;
    private javax.swing.JTextField hctflg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField mchAbNorm;
    private javax.swing.JTextField mchNormal;
    private javax.swing.JTextField mchcAbNorm;
    private javax.swing.JTextField mchcNormal;
    private javax.swing.JTextField mchcflg;
    private javax.swing.JTextField mchflg;
    private javax.swing.JTextField mcvAbNorm;
    private javax.swing.JTextField mcvNormal;
    private javax.swing.JTextField mcvflg;
    private javax.swing.JTextField meanPlateNormal;
    private javax.swing.JTextField meanplateflg;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField orderedTxt;
    private javax.swing.JTextField orderingDrTxt;
    private javax.swing.JTextField patientTxt;
    private javax.swing.JTextField physicianCopyTxt;
    private javax.swing.JTextField platecountNormal;
    private javax.swing.JTextField plateletflg;
    private javax.swing.JTextField queriesTxt;
    private javax.swing.JTextField rbcflg;
    private javax.swing.JTextField rbcnormal;
    private javax.swing.JTextField rdwNormal;
    private javax.swing.JTextField rdwflg;
    private javax.swing.JTextField receivedDate;
    private javax.swing.JTextField receivedTime;
    private javax.swing.JTextField sexTxt;
    private javax.swing.JTextField specTxt;
    private javax.swing.JTextField specimenTxt;
    private javax.swing.JTextField statusTxt;
    private javax.swing.JTextField tbcAbNorm;
    private javax.swing.JTextField wbcAbnorm;
    private javax.swing.JTextField wbcNormal;
    private javax.swing.JTextField wbcflg;
    // End of variables declaration//GEN-END:variables
}
