/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole.MedicalRecordsDetails;

import Business.Patient.Patient;
import javax.swing.JPanel;

/**
 *
 * @author Niranjanii
 */
public class ChloestralForm extends javax.swing.JPanel {

    /**
     * Creates new form ChloestralForm
     */
    
    private JPanel userProcessContainer;
    private Patient patient;
    private boolean cholesFlag;
    public ChloestralForm(JPanel userProcessContainer,Patient patient,boolean cholesFlag) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.patient=patient;
        this.cholesFlag=cholesFlag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hdlTxt = new javax.swing.JTextField();
        ldlTxt = new javax.swing.JTextField();
        triGlyTxt = new javax.swing.JTextField();
        tcTxt = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText(" Total Cholesterol");
        add(jLabel1);
        jLabel1.setBounds(230, 140, 150, 14);

        jLabel2.setText("HDL (High density lipoprotein)");
        add(jLabel2);
        jLabel2.setBounds(230, 190, 142, 14);

        jLabel3.setText("LDL (Low density lipoprotein)");
        add(jLabel3);
        jLabel3.setBounds(230, 230, 138, 14);

        jLabel4.setText("Triglycerides");
        add(jLabel4);
        jLabel4.setBounds(230, 270, 60, 14);
        add(hdlTxt);
        hdlTxt.setBounds(440, 190, 130, 20);
        add(ldlTxt);
        ldlTxt.setBounds(440, 220, 130, 20);
        add(triGlyTxt);
        triGlyTxt.setBounds(440, 260, 130, 20);
        add(tcTxt);
        tcTxt.setBounds(440, 140, 130, 20);

        clearBtn.setText("Clear");
        add(clearBtn);
        clearBtn.setBounds(420, 330, 90, 30);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn);
        addBtn.setBounds(290, 330, 90, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        tcTxt.getText();
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField hdlTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField ldlTxt;
    private javax.swing.JTextField tcTxt;
    private javax.swing.JTextField triGlyTxt;
    // End of variables declaration//GEN-END:variables
}
