/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole.MedicalRecordsDetails;

import Business.GFRTest.gfrTest;
import Business.Patient.Patient;
import javax.swing.JPanel;

/**
 *
 * @author Niranjanii
 */
public class GFRForm extends javax.swing.JPanel {

    /**
     * Creates new form GFRForm
     */
     private JPanel userProcessContainer;
    private Patient patient;
    private boolean gfrFlag;
    
    public GFRForm(JPanel userProcessContainer,Patient patient,boolean gfrFlag) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.patient=patient;
        this.gfrFlag = gfrFlag;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        serumSd = new javax.swing.JTextField();
        bunSd = new javax.swing.JTextField();
        bunMean = new javax.swing.JTextField();
        ktMean = new javax.swing.JTextField();
        ktSd = new javax.swing.JTextField();
        gfrMean = new javax.swing.JTextField();
        gfrSd = new javax.swing.JTextField();
        gfrMdrdMean = new javax.swing.JTextField();
        gfrMdrdSd = new javax.swing.JTextField();
        ccrMean = new javax.swing.JTextField();
        ccrcSd = new javax.swing.JTextField();
        ccrCockMean = new javax.swing.JTextField();
        ccrCockSd = new javax.swing.JTextField();
        ccrcUreaSD = new javax.swing.JTextField();
        ccrcUreaMean = new javax.swing.JTextField();
        serumMean = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        hospital = new javax.swing.JTextField();
        doctor = new javax.swing.JTextField();

        setLayout(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Measurement");
        add(jLabel10);
        jLabel10.setBounds(190, 160, 120, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Mean :");
        add(jLabel11);
        jLabel11.setBounds(380, 160, 120, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("SD :");
        add(jLabel12);
        jLabel12.setBounds(540, 160, 120, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setText("Range :");
        add(jLabel13);
        jLabel13.setBounds(700, 160, 120, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setText("Serum Creatinie (mg/dL) :");
        add(jLabel14);
        jLabel14.setBounds(130, 220, 180, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setText("BUN(mg/dL) :");
        add(jLabel15);
        jLabel15.setBounds(190, 280, 120, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setText("Kt/V urea :");
        add(jLabel16);
        jLabel16.setBounds(190, 340, 120, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel17.setText("GFR (125 I-iothalamate clearance)*  :");
        add(jLabel17);
        jLabel17.setBounds(190, 440, 120, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel18.setText("GFR(MDRD Study Equation)* :");
        add(jLabel18);
        jLabel18.setBounds(190, 490, 120, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel19.setText("Ccr(Measured)* :");
        add(jLabel19);
        jLabel19.setBounds(190, 540, 120, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel20.setText("Ccr(Cockcroft-Gault Equation)* :");
        add(jLabel20);
        jLabel20.setBounds(190, 570, 120, 60);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel21.setText("* Units for clearence Measurements: mL/min/1.73m2");
        add(jLabel21);
        jLabel21.setBounds(190, 680, 410, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel22.setText("0.8 - 3.2");
        add(jLabel22);
        jLabel22.setBounds(700, 340, 120, 30);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel23.setText("4.1 - 18.2");
        add(jLabel23);
        jLabel23.setBounds(690, 440, 120, 30);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel24.setText("4.9 - 18.3");
        add(jLabel24);
        jLabel24.setBounds(690, 490, 120, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel25.setText("3.9 - 25.7");
        add(jLabel25);
        jLabel25.setBounds(690, 540, 120, 30);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel26.setText("6.2 - 25.3");
        add(jLabel26);
        jLabel26.setBounds(690, 580, 120, 30);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel27.setText("3.3 - 18.8");
        add(jLabel27);
        jLabel27.setBounds(690, 620, 120, 30);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel28.setText("3.3 - 11.5");
        add(jLabel28);
        jLabel28.setBounds(700, 210, 120, 30);
        add(serumSd);
        serumSd.setBounds(540, 220, 140, 30);
        add(bunSd);
        bunSd.setBounds(530, 280, 140, 30);
        add(bunMean);
        bunMean.setBounds(370, 280, 140, 30);
        add(ktMean);
        ktMean.setBounds(370, 340, 140, 30);
        add(ktSd);
        ktSd.setBounds(530, 340, 140, 30);
        add(gfrMean);
        gfrMean.setBounds(370, 440, 140, 30);
        add(gfrSd);
        gfrSd.setBounds(530, 440, 140, 30);
        add(gfrMdrdMean);
        gfrMdrdMean.setBounds(370, 490, 140, 30);
        add(gfrMdrdSd);
        gfrMdrdSd.setBounds(530, 490, 140, 30);
        add(ccrMean);
        ccrMean.setBounds(370, 540, 140, 30);
        add(ccrcSd);
        ccrcSd.setBounds(530, 540, 140, 30);
        add(ccrCockMean);
        ccrCockMean.setBounds(370, 580, 140, 30);
        add(ccrCockSd);
        ccrCockSd.setBounds(530, 580, 140, 30);
        add(ccrcUreaSD);
        ccrcUreaSD.setBounds(530, 620, 140, 30);
        add(ccrcUreaMean);
        ccrcUreaMean.setBounds(370, 620, 140, 30);
        add(serumMean);
        serumMean.setBounds(370, 220, 140, 30);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel29.setText("28 - 118");
        add(jLabel29);
        jLabel29.setBounds(700, 280, 120, 30);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel30.setText("(Ccr + Curea) 2 * :");
        add(jLabel30);
        jLabel30.setBounds(190, 620, 120, 30);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        add(Add);
        Add.setBounds(820, 500, 120, 40);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel31.setText("Doctor :");
        add(jLabel31);
        jLabel31.setBounds(510, 30, 180, 30);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel32.setText("Hospital :");
        add(jLabel32);
        jLabel32.setBounds(510, 80, 180, 30);
        add(hospital);
        hospital.setBounds(750, 80, 140, 30);
        add(doctor);
        doctor.setBounds(750, 30, 140, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        gfrFlag = true;
        gfrTest gfrtst=patient.getMedicalRecord().getGfrDir().addgfrTest();
        gfrtst.setBunMean(bunMean.getText());
        gfrtst.setCcrCUreaMean(ccrcUreaMean.getText());
        gfrtst.setCcrCockcroftEquationMean(ccrCockMean.getText());
        gfrtst.setCcrMeasuredMean(ccrMean.getText());
        gfrtst.setGfrIothalamateMean(gfrMean.getText());
        gfrtst.setGfrMDRDMean(gfrMdrdMean.getText());
        gfrtst.setKtvUreaMean(ktMean.getText());
        gfrtst.setSerumCreatinineMean(serumMean.getText());
        
        gfrtst.setBunSd(bunSd.getText());
        gfrtst.setCcrCUreaSd(ccrcUreaSD.getText());
        gfrtst.setCcrCockcroftEquationSd(ccrCockSd.getText());
        gfrtst.setCcrMeasuredSd(ccrcSd.getText());
        gfrtst.setGfrIothalamateSd(gfrSd.getText());
        gfrtst.setGfrMDRDSd(gfrMdrdSd.getText());
        gfrtst.setKtvUreaSd(ktSd.getText());
        gfrtst.setSerumCreatinineSd(serumSd.getText());
    }//GEN-LAST:event_AddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField bunMean;
    private javax.swing.JTextField bunSd;
    private javax.swing.JTextField ccrCockMean;
    private javax.swing.JTextField ccrCockSd;
    private javax.swing.JTextField ccrMean;
    private javax.swing.JTextField ccrcSd;
    private javax.swing.JTextField ccrcUreaMean;
    private javax.swing.JTextField ccrcUreaSD;
    private javax.swing.JTextField doctor;
    private javax.swing.JTextField gfrMdrdMean;
    private javax.swing.JTextField gfrMdrdSd;
    private javax.swing.JTextField gfrMean;
    private javax.swing.JTextField gfrSd;
    private javax.swing.JTextField hospital;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JTextField ktMean;
    private javax.swing.JTextField ktSd;
    private javax.swing.JTextField serumMean;
    private javax.swing.JTextField serumSd;
    // End of variables declaration//GEN-END:variables
}
