/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bloodbank;

import Business.Bloodbankinventory.Bloodtypeandquantity;
import Business.Enterprise.Enterprise;
import Business.Organization.BloodbankOrg;
import Business.bloodbankcampaign.bloodbankcampaignmember;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class AddbloodtotheInventory extends javax.swing.JPanel {

    /**
     * Creates new form AddbloodtotheInventory
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private BloodbankOrg bloodbankOrg;
    private bloodbankcampaignmember bbcm;
    
    AddbloodtotheInventory(JPanel userProcessContainer, Enterprise enterprise, BloodbankOrg bloodbankOrg, bloodbankcampaignmember bbcm) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.bloodbankOrg=bloodbankOrg;
        this.bbcm=bbcm;
        
        jTextField1.setText(bbcm.getFirstName());
        jTextField2.setText(bbcm.getUseraccount().getPatient().getMedicalRecord().getBloodGroup());
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("First Name:");
        add(jLabel1);
        jLabel1.setBounds(111, 85, 120, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Blood Group:");
        add(jLabel2);
        jLabel2.setBounds(111, 123, 120, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Quantity in Ltrs:");
        add(jLabel3);
        jLabel3.setBounds(91, 161, 140, 20);

        jTextField1.setEditable(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(249, 82, 125, 20);

        jTextField2.setEditable(false);
        add(jTextField2);
        jTextField2.setBounds(249, 120, 125, 20);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        add(jTextField3);
        jTextField3.setBounds(249, 158, 125, 20);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Add to the Inventory");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(184, 238, 200, 29);

        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(10, 30, 110, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 0, 1030, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        Bloodtypeandquantity btq1=new Bloodtypeandquantity();
        int c=0;
        
        for(Bloodtypeandquantity btq:bloodbankOrg.getBbi().getBloodbankinv()){
            if(btq.getBloodtype().equals(bbcm.getUseraccount().getPatient().getMedicalRecord().getBloodGroup()));
            {
                btq1=btq;
                int q=btq.getQuantity();
                int q2=Integer.parseInt(jTextField3.getText());
                int fq=q+q2;
                btq.setQuantity(fq);
                c=1;
            }
           
        }
        
         if(c==0){
                btq1.setBloodtype(bbcm.getUseraccount().getPatient().getMedicalRecord().getBloodGroup());
                btq1.setQuantity(Integer.parseInt(jTextField3.getText()));
                bloodbankOrg.getBbi().Addblood(btq1);
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Enter the values");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
              char vchar = evt.getKeyChar();
       if(! (Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
           
	     char vchar = evt.getKeyChar();
       if(! (Character.isAlphabetic(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_jTextField3KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
