/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.*;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author akshayasuresh
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
   

    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization doctorOrganization, Enterprise enterprise,EcoSystem system) {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.organization = doctorOrganization;
            this.enterprise = enterprise;
            this.userAccount = account;
            this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emergenyModeBtn = new javax.swing.JButton();
        generalModeBtn = new javax.swing.JButton();
        emergenyModeBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);

        emergenyModeBtn.setBackground(new java.awt.Color(255, 204, 51));
        emergenyModeBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        emergenyModeBtn.setText("Emergency Mode");
        emergenyModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergenyModeBtnActionPerformed(evt);
            }
        });
        add(emergenyModeBtn);
        emergenyModeBtn.setBounds(700, 270, 210, 40);

        generalModeBtn.setBackground(new java.awt.Color(255, 204, 51));
        generalModeBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        generalModeBtn.setText("General Mode");
        generalModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalModeBtnActionPerformed(evt);
            }
        });
        add(generalModeBtn);
        generalModeBtn.setBounds(420, 270, 210, 40);

        emergenyModeBtn1.setBackground(new java.awt.Color(255, 204, 51));
        emergenyModeBtn1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        emergenyModeBtn1.setText("Notifications");
        emergenyModeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergenyModeBtn1ActionPerformed(evt);
            }
        });
        add(emergenyModeBtn1);
        emergenyModeBtn1.setBounds(1010, 270, 210, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, -80, 1830, 1180);
    }// </editor-fold>//GEN-END:initComponents

    private void emergenyModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergenyModeBtnActionPerformed
         EmergencyModeJPanel emergencyModeJPanel = new EmergencyModeJPanel(system,userProcessContainer,  userAccount, organization, enterprise);
        userProcessContainer.add("EmergencyModeJPanel", emergencyModeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_emergenyModeBtnActionPerformed

    private void generalModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalModeBtnActionPerformed
        // TODO add your handling code here:
        GeneralModeJPanel generalModeJPanel = new GeneralModeJPanel(system,userProcessContainer,  userAccount, organization, enterprise);
        userProcessContainer.add("GeneralModeJPanel", generalModeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_generalModeBtnActionPerformed

    private void emergenyModeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergenyModeBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergenyModeBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emergenyModeBtn;
    private javax.swing.JButton emergenyModeBtn1;
    private javax.swing.JButton generalModeBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
