/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
//import UserInterface.OrganHealth.OrganHealthJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Niranjanii
 */
public class InPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InPatientJPanel
     */
    JPanel userProcessContainer;
    Patient patient;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    public InPatientJPanel(JPanel userProcessContainer, Patient patient,Enterprise enterprise, UserAccount userAccount, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient=patient;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        this.system=ecosystem;
        sendRequest.setVisible(false);
        addMedicalRecords.setVisible(false);
     //   wholeBodyCheckup.setVisible(false);
            ecgDetails.setVisible(false);
            gfrDetails.setVisible(false);
            organDetails.setVisible(false);
            
        bloodTest.setVisible(false);
        vaccineDetails.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sendRequest = new javax.swing.JButton();
        View = new javax.swing.JButton();
        addMedicalRecords = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        vaccineDetails = new javax.swing.JButton();
        bloodTest = new javax.swing.JButton();
        gfrDetails = new javax.swing.JButton();
        ecgDetails = new javax.swing.JButton();
        organDetails = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);

        sendRequest.setBackground(new java.awt.Color(255, 204, 102));
        sendRequest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sendRequest.setText("Send Test Request to Lab");
        sendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestActionPerformed(evt);
            }
        });
        add(sendRequest);
        sendRequest.setBounds(100, 320, 230, 50);

        View.setBackground(new java.awt.Color(255, 204, 102));
        View.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        View.setText("View/Edit Record");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        add(View);
        View.setBounds(570, 180, 230, 50);

        addMedicalRecords.setBackground(new java.awt.Color(255, 204, 102));
        addMedicalRecords.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        addMedicalRecords.setText("Add Medical Records");
        addMedicalRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicalRecordsActionPerformed(evt);
            }
        });
        add(addMedicalRecords);
        addMedicalRecords.setBounds(400, 320, 230, 50);

        Add.setBackground(new java.awt.Color(255, 204, 102));
        Add.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Add.setText("Add Record");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        add(Add);
        Add.setBounds(150, 180, 230, 50);

        vaccineDetails.setBackground(new java.awt.Color(255, 204, 102));
        vaccineDetails.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        vaccineDetails.setText("Vaccine Details");
        vaccineDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineDetailsActionPerformed(evt);
            }
        });
        add(vaccineDetails);
        vaccineDetails.setBounds(710, 390, 230, 50);

        bloodTest.setBackground(new java.awt.Color(255, 204, 102));
        bloodTest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bloodTest.setText("Blood Test Details");
        bloodTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTestActionPerformed(evt);
            }
        });
        add(bloodTest);
        bloodTest.setBounds(400, 320, 230, 50);

        gfrDetails.setBackground(new java.awt.Color(255, 204, 102));
        gfrDetails.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        gfrDetails.setText("GFR Details");
        gfrDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gfrDetailsActionPerformed(evt);
            }
        });
        add(gfrDetails);
        gfrDetails.setBounds(400, 390, 230, 50);

        ecgDetails.setBackground(new java.awt.Color(255, 204, 102));
        ecgDetails.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ecgDetails.setText("ECG Details");
        ecgDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecgDetailsActionPerformed(evt);
            }
        });
        add(ecgDetails);
        ecgDetails.setBounds(100, 390, 230, 50);

        organDetails.setBackground(new java.awt.Color(255, 204, 102));
        organDetails.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        organDetails.setText("Organ Details");
        organDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organDetailsActionPerformed(evt);
            }
        });
        add(organDetails);
        organDetails.setBounds(710, 320, 230, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void sendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestActionPerformed
        SendRequestToLabJPanel sendRequestToLabJPanel = new SendRequestToLabJPanel( userProcessContainer,  patient, enterprise,  userAccount, system);
        userProcessContainer.add("requestToLabAssistant", sendRequestToLabJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_sendRequestActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
         sendRequest.setVisible(false);
        addMedicalRecords.setVisible(false);
        //wholeBodyCheckup.setVisible(true);
        bloodTest.setVisible(true);
        vaccineDetails.setVisible(true);
        ecgDetails.setVisible(true);
        gfrDetails.setVisible(true);
        organDetails.setVisible(true);
    }//GEN-LAST:event_ViewActionPerformed

    private void addMedicalRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicalRecordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMedicalRecordsActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        sendRequest.setVisible(true);
        addMedicalRecords.setVisible(true);
       // wholeBodyCheckup.setVisible(false);
        bloodTest.setVisible(false);
        vaccineDetails.setVisible(false);
        ecgDetails.setVisible(false);
        gfrDetails.setVisible(false);
        organDetails.setVisible(false);
        
    }//GEN-LAST:event_AddActionPerformed

    private void vaccineDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineDetailsActionPerformed
      ListJPanel listJPanel = new ListJPanel(userProcessContainer,"VaccineTest",patient, enterprise,  userAccount, system);
            userProcessContainer.add("listJPanel", listJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_vaccineDetailsActionPerformed

    private void bloodTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTestActionPerformed
            ListJPanel listJPanel = new ListJPanel(userProcessContainer,"bloodTest",patient, enterprise,  userAccount, system);
            userProcessContainer.add("listJPanel", listJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_bloodTestActionPerformed

    private void gfrDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gfrDetailsActionPerformed
       ListJPanel listJPanel = new ListJPanel(userProcessContainer,"GFRTest",patient, enterprise,  userAccount, system);
            userProcessContainer.add("listJPanel", listJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_gfrDetailsActionPerformed

    private void ecgDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecgDetailsActionPerformed
        ListJPanel listJPanel = new ListJPanel(userProcessContainer,"ECGTest",patient, enterprise,  userAccount, system);
            userProcessContainer.add("listJPanel", listJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_ecgDetailsActionPerformed

    private void organDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organDetailsActionPerformed
//             OrganHealthJPanel listJPanel = new OrganHealthJPanel(userProcessContainer,patient, enterprise,  userAccount, system);
//            userProcessContainer.add("listJPanel", listJPanel);
//            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//            layout.next(userProcessContainer);
    }//GEN-LAST:event_organDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton View;
    private javax.swing.JButton addMedicalRecords;
    private javax.swing.JButton bloodTest;
    private javax.swing.JButton ecgDetails;
    private javax.swing.JButton gfrDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton organDetails;
    private javax.swing.JButton sendRequest;
    private javax.swing.JButton vaccineDetails;
    // End of variables declaration//GEN-END:variables
}
