/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccountPermissionRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akshayasuresh
 */
public class DoctorRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorRequestJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientOrganization patientOrg;
   
    public DoctorRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, PatientOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.patientOrg= organization;
        populateRequestTable();
    }

 
    public void populateRequestTable(){
       DefaultTableModel model = (DefaultTableModel)permissionRequestJTable.getModel();
        
       model.setRowCount(0);

     for(UserAccount userAccountDetails:patientOrg.getUserAccountDirectory().getUserAccountList())
     {
         if(userAccount.getUsername().equals(userAccountDetails.getUsername()))
         {
            for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
                if(request instanceof AccountPermissionRequest)
                {
                  Object[] row = new Object[4];
                  row[0] = request;
                  row[1] = request.getSender().getPatient().getFirstName()+" "+request.getSender().getPatient().getLastName();
                  row[2] = request.getReceiver() == null ? null : request.getReceiver().getPatient().getFirstName()+" "+request.getSender().getPatient().getLastName();
                  row[3] = request.getStatus();

                  model.addRow(row);
                }
              } 
         }
     }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        permissionRequestJTable = new javax.swing.JTable();
        respondBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        Declined = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);

        refreshTestJButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton);
        refreshTestJButton.setBounds(570, 50, 81, 29);

        permissionRequestJTable.setBackground(new java.awt.Color(0, 0, 0));
        permissionRequestJTable.setForeground(new java.awt.Color(255, 255, 255));
        permissionRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(permissionRequestJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(160, 200, 630, 120);

        respondBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        respondBtn.setText("Accepted");
        respondBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respondBtnActionPerformed(evt);
            }
        });
        add(respondBtn);
        respondBtn.setBounds(470, 360, 130, 30);

        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(40, 50, 110, 27);

        Declined.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Declined.setText("Declined");
        Declined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeclinedActionPerformed(evt);
            }
        });
        add(Declined);
        Declined.setBounds(280, 360, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void respondBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respondBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = permissionRequestJTable.getSelectedRow();
         if (selectedRow < 0){
            return;
        }
        
        AccountPermissionRequest request = (AccountPermissionRequest)permissionRequestJTable.getValueAt(selectedRow, 0);
     
        request.setStatus("Accepted");
        request.setPermission("Accepted");
         /*int selectedRow = permissionRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        AccountPermissionRequest request = (AccountPermissionRequest)permissionRequestJTable.getValueAt(selectedRow, 0);
     
        request.setStatus("Processing");
        
        RespondDoctorRequestJPanel respondDoctorRequestJPanel = new RespondDoctorRequestJPanel(userProcessContainer, request);
        userProcessContainer.add("respondDoctorRequestJPanel", respondDoctorRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
        
    }//GEN-LAST:event_respondBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void DeclinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclinedActionPerformed
         int selectedRow = permissionRequestJTable.getSelectedRow();
         if (selectedRow < 0){
            return;
        }
        
        AccountPermissionRequest request = (AccountPermissionRequest)permissionRequestJTable.getValueAt(selectedRow, 0);
     
        request.setStatus("Declined");
         request.setPermission("Declined");
    }//GEN-LAST:event_DeclinedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Declined;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable permissionRequestJTable;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton respondBtn;
    // End of variables declaration//GEN-END:variables
}
