/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package UserInterface.OrganBank;



/**
 *
 * @author akshayasuresh
 */



public class ManageOrganRequesttJPanel extends javax.swing.JPanel {




    /**
     * Creates new form ManageOrganRequestJPanel
     */
    public ManageOrganRequesttJPanel() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organRequestJTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        findOrganBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        organAvailableJTable = new javax.swing.JTable();
        deliverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        organRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Doctor", "Hospital", "Network", "Organ needed", "Blood Type", "Medical ID", "Time frame", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organRequestJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(114, 87, 679, 224);

        backBtn.setBackground(new java.awt.Color(255, 204, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(0, 11, 164, 40);

        findOrganBtn.setBackground(new java.awt.Color(255, 204, 51));
        findOrganBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        findOrganBtn.setText("Find Organ");
        findOrganBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findOrganBtnActionPerformed(evt);
            }
        });
        add(findOrganBtn);
        findOrganBtn.setBounds(248, 329, 164, 40);

        processBtn.setBackground(new java.awt.Color(255, 204, 51));
        processBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });
        add(processBtn);
        processBtn.setBounds(459, 329, 164, 40);

        organAvailableJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Organ", "Organ ID", "Blood Type", "Use by", "Time left"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(organAvailableJTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(162, 415, 600, 166);

        deliverBtn.setBackground(new java.awt.Color(255, 204, 51));
        deliverBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        deliverBtn.setText("Get Information");
        deliverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverBtnActionPerformed(evt);
            }
        });
        add(deliverBtn);
        deliverBtn.setBounds(363, 623, 164, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, -80, 1830, 1180);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void findOrganBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findOrganBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findOrganBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processBtnActionPerformed

    private void deliverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliverBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deliverBtn;
    private javax.swing.JButton findOrganBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable organAvailableJTable;
    private javax.swing.JTable organRequestJTable;
    private javax.swing.JButton processBtn;
    // End of variables declaration//GEN-END:variables
}
