/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.OrganBank;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.OrganBankOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.OrganBank.OrganRegistration.DonorRegistrationJPanel;
import UserInterface.OrganBank.OrganRegistration.RecipientRegistrationJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author akshayasuresh
 */
public class OrganBankWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrganBankWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private OrganBankOrg organization;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    public OrganBankWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
            this.organization = (OrganBankOrg)organization;
            this.ecosystem = business;
            this.userAccount = account;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerDonorBtn = new javax.swing.JButton();
        viewOrgansBtn = new javax.swing.JButton();
        organRequestBtn = new javax.swing.JButton();
        registerRecipientBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        registerDonorBtn.setBackground(new java.awt.Color(255, 204, 51));
        registerDonorBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        registerDonorBtn.setText("Register Donor");
        registerDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerDonorBtnActionPerformed(evt);
            }
        });
        add(registerDonorBtn);
        registerDonorBtn.setBounds(480, 430, 210, 40);

        viewOrgansBtn.setBackground(new java.awt.Color(255, 204, 51));
        viewOrgansBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        viewOrgansBtn.setText("View Available Organs ");
        viewOrgansBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrgansBtnActionPerformed(evt);
            }
        });
        add(viewOrgansBtn);
        viewOrgansBtn.setBounds(480, 570, 210, 40);

        organRequestBtn.setBackground(new java.awt.Color(255, 204, 51));
        organRequestBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        organRequestBtn.setText("Manage Organ Request");
        organRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organRequestBtnActionPerformed(evt);
            }
        });
        add(organRequestBtn);
        organRequestBtn.setBounds(830, 570, 210, 40);

        registerRecipientBtn.setBackground(new java.awt.Color(255, 204, 51));
        registerRecipientBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        registerRecipientBtn.setText("Register Recipient");
        registerRecipientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerRecipientBtnActionPerformed(evt);
            }
        });
        add(registerRecipientBtn);
        registerRecipientBtn.setBounds(820, 430, 210, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, -40, 1660, 1260);
    }// </editor-fold>//GEN-END:initComponents

    private void registerDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerDonorBtnActionPerformed
        // TODO add your handling code here:
     DonorRegistrationJPanel donorRegistrationJPanel = new DonorRegistrationJPanel(userProcessContainer,  userAccount, organization, ecosystem);
        userProcessContainer.add("DonorRegistrationJPanel", donorRegistrationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_registerDonorBtnActionPerformed

    private void viewOrgansBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrgansBtnActionPerformed
        // TODO add your handling code here:
        ViewOrgansAvailableJPanel viewOrgansAvailableJPanel = new ViewOrgansAvailableJPanel(userProcessContainer,  userAccount, organization, ecosystem);
        userProcessContainer.add("ViewOrgansAvailableJPanel", viewOrgansAvailableJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
      
    }//GEN-LAST:event_viewOrgansBtnActionPerformed

    private void organRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organRequestBtnActionPerformed
        // TODO add your handling code here:
       ManageOrganRequestJPanel manageOrganRequestJPanel = new ManageOrganRequestJPanel(userProcessContainer,  userAccount, organization, ecosystem);
        userProcessContainer.add("ManageOrganRequestJPanel", manageOrganRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_organRequestBtnActionPerformed

    private void registerRecipientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerRecipientBtnActionPerformed
        // TODO add your handling code here:
        RecipientRegistrationJPanel recipientRegistrationJPanel = new RecipientRegistrationJPanel(userProcessContainer,  userAccount, organization, ecosystem);
        userProcessContainer.add("RecipientRegistrationJPanel", recipientRegistrationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_registerRecipientBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton organRequestBtn;
    private javax.swing.JButton registerDonorBtn;
    private javax.swing.JButton registerRecipientBtn;
    private javax.swing.JButton viewOrgansBtn;
    // End of variables declaration//GEN-END:variables
}
