/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;

import UserInterface.DoctorRole.OrganDonation.OrganDonationJPanel;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Niranjanii
 */
public class CheckInOrOutPatient extends javax.swing.JPanel {

    /**
     * Creates new form CheckInOrOutPatient
     */
    private JPanel userProcessContainer;
    private Patient patient;
     private Enterprise enterprise;
    private UserAccount userAccount;
    private UserAccount patientAccount;
    private EcoSystem system;
    public CheckInOrOutPatient(JPanel userProcessContainer,UserAccount patientAccount,Enterprise enterprise, UserAccount userAccount, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.patientAccount=patientAccount;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        this.system=ecosystem;
        patient = patientAccount.getPatient();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outPatientDet = new javax.swing.JButton();
        inPatientDet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(null);

        outPatientDet.setBackground(new java.awt.Color(255, 204, 102));
        outPatientDet.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        outPatientDet.setText("Out-Patient");
        outPatientDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outPatientDetActionPerformed(evt);
            }
        });
        add(outPatientDet);
        outPatientDet.setBounds(940, 240, 180, 50);

        inPatientDet.setBackground(new java.awt.Color(255, 204, 102));
        inPatientDet.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        inPatientDet.setText("In-Patient");
        inPatientDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPatientDetActionPerformed(evt);
            }
        });
        add(inPatientDet);
        inPatientDet.setBounds(730, 240, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imageedit_1_7751284971.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -150, 1730, 1450);
    }// </editor-fold>//GEN-END:initComponents

    private void outPatientDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outPatientDetActionPerformed

    }//GEN-LAST:event_outPatientDetActionPerformed

    private void inPatientDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPatientDetActionPerformed
       InPatientJPanel inPatientJPanel = new InPatientJPanel(userProcessContainer,patientAccount,enterprise,userAccount,system);
        userProcessContainer.add("requestToLabAssistant", inPatientJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);   
    }//GEN-LAST:event_inPatientDetActionPerformed


    private void organDonationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organDonationBtnActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_organDonationBtnActionPerformed





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inPatientDet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton outPatientDet;
    // End of variables declaration//GEN-END:variables
}
