/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabAssistant;

import Business.WorkQueue.TestRequest;

import UserInterface.PatientRole.MedicalRecordsDetails.ChloestralForm;
import UserInterface.PatientRole.MedicalRecordsDetails.ECGForm;
import UserInterface.PatientRole.MedicalRecordsDetails.GFRForm;
import UserInterface.PatientRole.MedicalRecordsDetails.MeldForm;

import UserInterface.PatientRole.MedicalRecordsDetails.VaccineReport;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
<<<<<<< HEAD
 * @author Niranjanii
=======
 * @author Admin
>>>>>>> 004c8f139fdd4c16081e30d71582e2f3b5c728f5
 */
public class ProcessRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessRequestJPanel
     */

     String[] selected;
      TestRequest request;
      JPanel userProcessContainer;
      boolean bloodFlag = false;
       boolean cholestralFlag = false;
       boolean ecgFlag = false;
       boolean gfrFlag = false;
       boolean meldFlag = false;
       boolean prescriptionFlag = false;
       boolean vaccineFlag = false;
     
    public ProcessRequestJPanel(String[] selected,TestRequest request,JPanel userProcessContainer) {
        initComponents();
        this.selected=selected;
        this.request=request;
        this.userProcessContainer=userProcessContainer;
        
        populateCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testTaken = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        addTest = new javax.swing.JButton();


        setLayout(null);

        add(testTaken);
        testTaken.setBounds(180, 40, 210, 30);

        jLabel1.setText("Test :");
        add(jLabel1);
        jLabel1.setBounds(110, 44, 50, 20);


        addTest.setText("Add Test details");
        addTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTestActionPerformed(evt);
            }
        });

        add(addTest);
        addTest.setBounds(310, 160, 110, 40);

    }// </editor-fold>//GEN-END:initComponents

    private void addTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTestActionPerformed
        String test = (String)testTaken.getSelectedItem();


         if(test.equals("Vaccine"))
        {
            VaccineReport vaccineReport = new VaccineReport(userProcessContainer,request.getPatient(),null,vaccineFlag,null);
            userProcessContainer.add("vaccineReport", vaccineReport);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else if(test.equals("GFR Test"))
        {

            GFRForm gfrForm = new GFRForm(userProcessContainer,request.getPatient(),null,gfrFlag,null);
            userProcessContainer.add("gfrForm", gfrForm);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else if(test.equals("ECG Test"))
        {

            ECGForm ecgForm = new ECGForm(userProcessContainer,request.getPatient(),null,null,ecgFlag);
            userProcessContainer.add("ecgForm", ecgForm);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else if(test.equals("MELD Test"))
        {
            MeldForm meldForm = new MeldForm(userProcessContainer,request.getPatient(),meldFlag);
            userProcessContainer.add("meldForm", meldForm);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else if(test.equals("Cholestral Test"))
        {
            ChloestralForm cholestralForm = new ChloestralForm(userProcessContainer,request.getPatient(),cholestralFlag);
            userProcessContainer.add("cholestralForm", cholestralForm);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_addTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> testTaken;
    // End of variables declaration//GEN-END:variables


    public void populateCombobox() {
        
       testTaken.removeAllItems();
         
            for(String test :selected)
            {
                testTaken.addItem(test);
            }
             if(bloodFlag)
            {
                testTaken.remove(1);
            }
         
    }

}
